// Compact facts per site for the AI-visibility brief (Claude Sonnet, low effort): numbers with their 95% range, per engine, stages / clusters,
// competitors, sources, lost questions with their demand, perception and wrong claims, AI referral traffic and revenue, crawler access,
// the market-wide index, alerts and the computed actions (v4.9).
return $('AI Metrics').all().map(i => { const m = i.json; const M = m.metrics; const T = m.traffic; const X = m.index; const A = m.access;
  const facts = { domain: m.domain, business: m.business_name || m.domain, week: m.checked_at.slice(0, 10), questions_tracked: m.questions.length,
    numbers: { named_in_pct: M.mention_rate, range_95: M.mention_ci, answers_counted: M.samples, of_which_daily_pulse: M.pulse_samples, cited_pct: M.citation_rate, share_of_voice: M.share_of_voice, visibility_score_0_100: M.visibility_score, avg_position: M.avg_rank, ai_overview_shown_pct: M.aio_presence, brand_recognised: M.brand, sentiment_minus100_to_100: M.sentiment_score },
    change_vs_last_week: M.delta ? { ...M.delta, note: M.delta.significant === true ? 'the change in "named" is statistically real' : M.delta.significant === false ? 'the change in "named" is within sampling noise: do not call it a trend' : 'too few answers last week to test' } : 'first run',
    note: 'rates use the past 7 days of answers (this week\'s run on ChatGPT, Gemini, Perplexity and Google AI Mode / AI Overview plus the daily pulse) and exclude the brand question; Claude and brand recognition are checked monthly',
    per_engine: Object.values(m.engines).map(e => e.name + ': named in ' + e.mention_rate + '% of ' + (e.samples != null ? e.samples : e.answered) + ' answers, cites your pages ' + e.cited + 'x' + (e.carried ? ' (monthly, last ' + String(e.checked_at || '').slice(0, 10) + ')' : '')),
    by_buyer_stage: (m.clusters.stages || []).map(s => s.key + ': named ' + s.mention_rate + '% (' + s.questions + ' questions' + (s.leader ? ', leader ' + s.leader : '') + ')'),
    by_topic: (m.clusters.clusters || []).slice(0, 6).map(s => s.key + ': named ' + s.mention_rate + '%' + (s.volume ? ', ' + s.volume + ' AI searches/mo' : '') + (s.leader ? ', leader ' + s.leader : '')),
    competitors: m.competitors.map(c => c.domain + ' ' + c.share + '% share (' + c.mentions + ' mentions)'),
    sources_ai_trusts: m.sources.slice(0, 10).map(s => s.domain + ' (' + s.kind + ', ' + s.citations + ' citations)'), your_cited_pages: m.our_pages.map(x => x.url + ' ' + x.citations + 'x'),
    questions_lost: m.gaps.map(g => g.prompt + (g.volume ? ' [' + g.volume + ' AI searches/mo]' : '') + ' → ' + g.competitors.slice(0, 3).join(', ')),
    what_ai_searched: (m.fanout || []).slice(0, 6).map(f => f.query),
    perception: { score: m.perception.score, positive: m.perception.positive, negative: m.perception.negative, words_ai_uses: m.perception.descriptors, wrong_claims: m.perception.issues.map(x => x.text + ' (' + x.engines.join(', ') + (x.new ? ', new' : '') + ')') },
    ai_referral_traffic: T && T.connected ? { last_28_days: { visits: T.sessions, key_events: T.key_events, revenue: T.revenue, change_pct: T.change_pct }, conversion_rate_pct: T.conv_rate, organic_conversion_rate_pct: T.organic_conv_rate, share_of_all_visits_pct: T.share_of_sessions, by_assistant: (T.assistants || []).slice(0, 5).map(a => a.name + ' ' + a.sessions), top_landing_pages: (T.landing || []).slice(0, 5).map(l => l.page + ' ' + l.sessions + (l.cited_by_ai ? ' (cited by AI)' : '')) } : (T ? 'not connected: ' + T.error : 'not connected'),
    crawler_access: A ? { ok: A.ok, answer_bots_allowed: A.answer_bots_ok + ' of ' + A.answer_bots, training_bots_blocked: A.training_blocked, llms_txt: A.llms_txt.found, issues: A.issues.map(x => x.level + ': ' + x.text) } : 'not checked',
    market_wide_index: X ? { platforms: X.platforms, your_share_pct: X.sov, answers_citing_you: X.answers_citing_you, brands: (X.brands || []).slice(0, 6).map(b => (b.domain || b.name) + ' ' + b.mentions + ' mentions' + (b.share != null ? ' (' + b.share + '%)' : '')), carried: !!X.carried } : null,
    demand: { ai_searches_behind_panel: M.demand_total, estimated_answers_naming_you: M.ai_impressions, in_questions_you_lose: M.lost_demand },
    market_view: m.market ? { topic: m.market.keyword, top_domains: (m.market.top || []).slice(0, 8).map(x => x.domain + ' ' + x.mentions), your_position: m.market.you || 'not in the list' } : null, alerts: m.alerts.map(a => a.text), computed_actions: m.actions.map(a => a.action + ' — ' + a.why) };
  return { json: { site_id: m.site_id, domain: m.domain, facts: JSON.stringify(facts) } }; });
