// Backlink report per site: monthly FULL report (profile vs last month, 12-month history, lost / new / spammy links, broken links to reclaim,
// link gap, unlinked mentions, the prospect pipeline with outreach drafts) or, on light weeks, a short ALERT e-mail when an important link was
// lost or spam arrived. Attachments: prospects.csv and, when needed, disavow-candidates.txt. Sites with nothing to report stay quiet.
// v4.10: every source merged (coverage per source and against Google's own sample), our own link check (verified / at risk / lost with the
// reason), the best links by SEO / referral / brand value, links that send visits, anchors, competitors' new links, "best X" lists that name
// competitors and not you, the gap from DataForSEO and Common Crawl, follow-up drafts, contacts, and the data credits the sources ask for.
// ---- shared report helpers (inlined by the build): the same look as the Site Tracker report ----
const esc = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const n = (v) => (Number(v) || 0).toLocaleString('en-GB');
const td = 'style="padding:4px 8px;border:1px solid #cbd5e1;font-size:13px;vertical-align:top"', th = 'style="padding:4px 8px;border:1px solid #cbd5e1;background:#f1f5f9;text-align:left;font-size:12px"';
const table = (headers, rows, empty) => rows.length ? '<table style="border-collapse:collapse;margin:6px 0;max-width:100%">' + '<tr>' + headers.map(h => '<th ' + th + '>' + esc(h) + '</th>').join('') + '</tr>' + rows.map(r => '<tr>' + r.map(c => '<td ' + td + '>' + c + '</td>').join('') + '</tr>').join('') + '</table>' : '<p style="color:#64748b;font-size:13px">' + esc(empty || 'nothing to show') + '</p>';
const tile = (label, value, delta, color) => '<td style="padding:8px 12px;border:1px solid #e2e8f0;min-width:110px;vertical-align:top"><div style="font-size:11px;color:#64748b;text-transform:uppercase">' + esc(label) + '</div><div style="font-size:20px;font-weight:700">' + value + '</div><div style="font-size:12px;color:' + (color || '#475569') + '">' + delta + '</div></td>';
const h3 = (t) => '<h3 style="margin:18px 0 4px;font-size:15px;color:#0f172a">' + esc(t) + '</h3>';
const p_ = (t, muted) => '<p style="margin:4px 0;font-size:13px' + (muted ? ';color:#64748b' : '') + '">' + t + '</p>';
const pathOf = (u) => { const p = String(u || '').replace(/^https?:\/\/[^\/]+/i, ''); return p || '/'; };
const link = (u, label) => u ? '<a href="' + esc(u) + '" style="color:#1d4ed8">' + esc(label || pathOf(u)) + '</a>' : '—';
const dpts = (v) => v == null ? '' : (v > 0 ? '<span style="color:#15803d">▲ ' + v + ' pts</span>' : v < 0 ? '<span style="color:#b91c1c">▼ ' + Math.abs(v) + ' pts</span>' : 'no change');
const briefBox = (b) => b ? '<div style="background:#f8fafc;border-left:4px solid #1d4ed8;padding:10px 12px;margin:8px 0"><div style="font-weight:700;font-size:15px">' + esc(b.headline) + '</div><p style="margin:6px 0 0;font-size:13px">' + esc(b.summary) + '</p></div>' : '';
const alertBox = (alerts) => (alerts || []).length ? '<div style="background:#fef2f2;border-left:4px solid #b91c1c;padding:8px 12px;margin:8px 0">' + alerts.map(a => '<div style="font-size:13px">⚠ ' + esc(a.text || a) + '</div>').join('') + '</div>' : '';
const wrapDoc = (title, body) => '<!DOCTYPE html><html><head><meta charset="utf-8"><title>' + esc(title) + '</title></head><body style="margin:24px">' + body + '</body></html>';
const b64 = (s) => Buffer.from(String(s), 'utf8').toString('base64');

const sites = $('Parse Backlinks').all().map(i => i.json);
let rows = []; try { rows = $('Prospect Rows').all().map(i => i.json).filter(r => !r.skip); } catch (e) {}
let stored = []; try { stored = $('Load Link Prospects').all().map(i => i.json).filter(x => x && x.prospect_domain); } catch (e) {}
const csvCell = (v) => '"' + String(v == null ? '' : v).replace(/"/g, '""') + '"';
const TYPE = { lost: 'Lost link — ask to restore', mention: 'Unlinked mention — ask for the link', list: '"Best of" list without you', comp_new: 'Just linked to a competitor', gap: 'Links to competitors', ai_source: 'Cited by AI answers', reclaim: 'Broken page — redirect' };
const REASON = { link_removed: 'link removed from the page', page_gone: 'the page is gone (404 / 410)', domain_gone: 'the site is gone', not_seen: 'no source has seen it for 4 months', reported_lost: 'reported lost by the index — being checked' };
const ACTION = { link_removed: 'Ask the editor to restore it (draft below)', page_gone: 'Ask whether the content moved; offer the link for the new page', domain_gone: 'Nothing to do', not_seen: 'Check the page by hand', reported_lost: 'Checked again next week' };
const SRC = [['dfs', 'DataForSEO index'], ['bing', 'Bing Webmaster Tools'], ['gsc', 'Google Search Console (upload)'], ['ga4', 'GA4 referrals (visits)'], ['cc', 'Common Crawl web graph'], ['wiki', 'Wikipedia'], ['hn', 'Hacker News'], ['news', 'News (GDELT)'], ['web', 'Web search'], ['import', 'Other upload']];
const vtag = (v) => ({ found: '<span style="color:#15803d">✓ on the page</span>', missing: '<span style="color:#b91c1c">not on the page</span>', gone: '<span style="color:#b91c1c">page gone</span>', blocked: '<span style="color:#64748b">bot-blocked (not checked)</span>', js: '<span style="color:#64748b">needs JavaScript</span>', error: '<span style="color:#64748b">error</span>' })[v] || '<span style="color:#64748b">not checked yet</span>';
return sites.filter(s => s.deliver).map(s => {
  const S = s.summary, P = s.previous, C = s.coverage || {}; const full = s.mode === 'full'; const st = C.status || {};
  const pipe = [...rows.filter(r => r.site_id === s.site_id), ...stored.filter(x => x.site_id === s.site_id && !rows.some(r => r.site_id === s.site_id && r.prospect_domain === x.prospect_domain && r.type === x.type))];
  const won = pipe.filter(r => r.status === 'won' && String(r.won_at || '').slice(0, 10) === s.checked_at.slice(0, 10));
  const counts = ['new', 'contacted', 'won', 'rejected', 'ignored'].map(x => x + ' ' + pipe.filter(r => (r.status || 'new') === x).length).join(' · ');
  const dv = (cur, prev) => P ? (cur - prev > 0 ? '<span style="color:#15803d">+' + n(cur - prev) + '</span>' : cur - prev < 0 ? '<span style="color:#b91c1c">' + n(cur - prev) + '</span>' : 'no change') : 'first check';
  const drCol = s.dr_enabled; const auth = (x) => { const a = Number(x.domain_rank ?? x.authority ?? x.rank) || 0, d = drCol && x.dr !== '' && x.dr != null && Number(x.dr) > 0 ? 'DR ' + n(x.dr) : ''; return a > 0 ? n(a) + (d ? ' · ' + d : '') : (d || '—'); };   // free runs have no DataForSEO authority: DR alone
  const L = s.ledger_rows || [];
  let html = '<div style="font-family:Segoe UI,Helvetica,Arial,sans-serif;color:#0f172a;max-width:900px">';
  html += '<h2 style="margin:0 0 2px;font-size:20px">' + (full ? 'Backlinks: ' : 'Backlink alert: ') + esc(s.domain) + '</h2>' + p_(esc(s.checked_at.slice(0, 10)) + ' · changes since ' + esc(s.since.slice(0, 10)) + (full ? ' · monthly report' : ' · weekly watch') + (s.on_demand ? ' · on-demand run' : ''), true);
  html += alertBox(s.alerts.filter(a => full || a.level !== 'low'));
  if (s.free_only) html += p_('<b>Free sources only</b> (asked on demand): Bing, your Search Console upload, GA4, Common Crawl, Wikipedia, Hacker News, news and web search, each important link checked on its page. No DataForSEO and no AI drafts: this check cost $0.', true);
  else if (!S.available) html += p_('The DataForSEO Backlinks API returned no summary (' + esc(S.error || 'no data') + '); the other sources are below.', true);
  html += '<table style="border-collapse:collapse;margin:8px 0"><tr>' + tile('Referring sites (all sources)', n(C.union), P && P.union_domains ? dv(C.union, P.union_domains) : (S.available ? 'DataForSEO alone: ' + n(S.referring_domains) : 'free sources')) + tile('Best links', n(s.best_links), 'SEO value 50+') +
    tile('Checked on the page', n(C.verified), C.checked_now ? n(C.checked_now) + ' checked this run' : '') + tile('Visits from links', n(s.referral.visits), 'past year · ' + n(s.referral.visits_28d) + ' in 28 days') +
    (S.available ? tile('Authority (0-1000)', n(S.rank), P && P.rank ? dv(S.rank, P.rank) : '') + tile('Spam score', S.spam_score + '/100', S.spam_score >= 40 ? '<span style="color:#b91c1c">high</span>' : 'ok') : tile('Authority (0-1000)', '—', 'DataForSEO: monthly full run')) + '</tr></table>';
  // lost and at risk
  const lostC = s.lost.filter(l => !l.pending);
  if (lostC.length || !full) html += h3('Links lost (confirmed by two checks)') + table(['From', 'Authority', 'Pointed to', 'Why', 'What to do'], lostC.slice(0, 15).map(l => [l.from_url ? link(l.from_url, l.from_domain) : esc(l.from_domain), auth(l), esc(pathOf(l.to_url)), esc(REASON[l.reason] || l.reason), esc(ACTION[l.reason] || '')]), 'none');
  if (s.at_risk.length) html += p_('Not found on their page this week, checked again next week before they count as lost: ' + esc(s.at_risk.slice(0, 10).map(a => a.ref_domain).join(', ')) + '.', true);
  if (s.rel_changed.length) html += h3('Links that changed') + table(['Site', 'Page', 'Now'], s.rel_changed.map(r => [esc(r.ref_domain), link(r.url), esc(r.rel)]));
  if (full) {
    // coverage
    const covRows = SRC.filter(([k]) => (C.per_source || {})[k] || ['dfs', 'bing', 'gsc', 'ga4', 'cc'].includes(k)).map(([k, label]) => {
      const note = k === 'bing' ? (st.bing && st.bing.enabled ? (st.bing.connected ? (!(Number(st.bing.links) > 0) ? 'connected; Bing reports no links to this site yet (new sites in Bing: allow a few weeks)' : '') : (st.bing.in_account === false ? 'site not in the Bing account: add it (Search Console import) or have its owner add the account as a user' : esc(st.bing.error || 'not connected'))) : 'off: set SEO_BING_WEBMASTER_API_KEY')
        : k === 'gsc' ? ((st.gsc || {}).uploaded_at ? 'export of ' + esc(String(st.gsc.uploaded_at).slice(0, 10)) : 'upload the Links export in the app (Backlinks → Add Search Console links)')
        : k === 'ga4' ? ((st.ga4 || {}).connected ? (st.ga4.excluded && st.ga4.excluded.length ? 'not links: ' + esc(st.ga4.excluded.slice(0, 4).join(', ')) : '') : ((st.ga4 || {}).property ? esc(st.ga4.error || 'no answer') : 'connect GA4 through "Track my site"'))
        : k === 'cc' ? ((st.cc || {}).release ? 'release ' + esc(st.cc.release) : 'the monthly linkgraph job has not run yet') : '';
      return [esc(label), n((C.per_source || {})[k] || 0), n((C.only_in || {})[k] || 0), note]; });
    html += h3('Where the links were found') + table(['Source', 'Referring sites', 'Only this source', 'Note'], covRows) +
      p_(C.gsc_sample ? 'Of the ' + n(C.gsc_sample) + ' sites in Google\'s own sample (Search Console), DataForSEO sees <b>' + C.dfs_sees_google + '%</b>; at least one other source confirms ' + C.all_see_google + '%.' : 'Upload the Search Console Links export to measure how much of Google\'s view each source covers.', true) +
      p_('DataForSEO finds ' + C.dfs_share + '% of the ' + n(C.union) + ' referring sites; the rest come from the other sources.' + (C.social ? ' Social networks (not counted): ' + n(C.social) + '.' : ''), true);
    if (s.wins.length) html += h3('Wins') + table(['Site', 'Page', ''], s.wins.slice(0, 12).map(w => [esc(w.ref_domain), link(w.url), w.why === 'restored' ? 'restored' : 'new' + (w.link_type ? ' · ' + esc(w.link_type) : '') + (w.seo ? ' · value ' + w.seo : '')]));
    const best = L.filter(r => r.status !== 'lost' && r.kind === 'web').sort((a, b) => b.seo_value - a.seo_value).slice(0, 15);
    html += h3('Best links') + table(['From', 'Value (SEO / visits / brand)', 'Type', 'Placement', 'Authority', 'Check'], best.map(r => [link(r.from_url || ('https://' + r.ref_domain + '/'), r.ref_domain), r.seo_value + ' / ' + r.referral_value + ' / ' + r.brand_value, esc(r.link_type || '—') + (r.rel && r.rel !== 'follow' ? ' · ' + esc(r.rel) : ''), esc(r.placement || '—'), auth(r), vtag(r.verify)]), 'no links yet');
    const sending = L.filter(r => r.visits > 0).sort((a, b) => b.visits - a.visits).slice(0, 10);
    if (sending.length) html += h3('Links that send visits (GA4, past year)') + table(['From', 'Visits', 'Key events', 'Page'], sending.map(r => [esc(r.ref_domain), n(r.visits), n(r.key_events), link(r.from_url)]));
    if (s.timeseries.length) html += h3('Last 12 months (DataForSEO index)') + table(['Month', 'Referring domains', 'Backlinks'], s.timeseries.slice(-12).map(t => [esc(t.month), n(t.referring_domains), n(t.backlinks)]));
    html += h3('New links') + table(['From', 'Authority', 'Anchor', 'First seen', ''], s.new_links.slice(0, 20).map(l => [l.from_url ? link(l.from_url, l.from_domain) : esc(l.from_domain), auth(l), esc(l.anchor), esc(l.first_seen), l.spammy ? '<span style="color:#b91c1c">spammy</span>' : (l.dofollow ? 'follow' : 'nofollow') + (l.verified ? ' · ' + vtag(l.verified) : '')]), 'no new links since the last check');
    html += h3('Links to broken pages (reclaim with a 301)') + table(['Broken page', 'Status', 'Links', 'From', 'Redirect to'], s.reclaim.map(r => [esc(pathOf(r.broken_url)), esc(r.status || 'error'), n(r.links), esc(r.domains.join(', ')), link(r.redirect_to)]), 'none — every linked page works');
    const K = (s.anchors || {}).kinds || {}; const kt = Object.values(K).reduce((a, b) => a + b, 0);
    if (kt) html += h3('Anchor texts') + p_(['brand', 'url', 'generic', 'money', 'image_or_empty'].filter(k => K[k]).map(k => esc({ brand: 'your name', url: 'web address', generic: 'generic ("here", "website")', money: 'keyword', image_or_empty: 'image / empty' }[k]) + ' ' + Math.round(100 * K[k] / kt) + '%').join(' · ') + ((K.money || 0) / kt > 0.3 && kt >= 10 ? ' — <b>keyword anchors are over 30%</b>: ask new links to use your name or the page title.' : ''), true) + table(['Anchor', 'Referring domains', 'Kind'], ((s.anchors || {}).top || []).slice(0, 10).map(a => [esc(a.anchor), n(a.referring_domains), esc(a.kind)]));
    if (s.comp_new.length) html += h3('Sites that just linked to a competitor') + table(['Site', 'Linked to', 'When', 'Page', 'Authority'], s.comp_new.slice(0, 12).map(c => [esc(c.domain), esc(c.competitor), esc(c.first_seen), link(c.url, c.title || c.url), auth(c)]));
    if (s.lists.length) html += h3('"Best of" lists') + table(['Page', 'Names competitors', 'You'], s.lists.slice(0, 10).map(l => [link(l.url, l.title || l.url), esc(l.competitors.join(', ') || '—'), l.linked ? '<span style="color:#15803d">linked</span>' : l.named ? 'named, no link' : '<b>missing</b>']));
    html += h3('Link gap: sites that link to ' + (s.competitors.length ? s.competitors.join(', ') : 'your competitors') + ' but not to you') + (s.gap_stored ? p_('DataForSEO gap from ' + esc(s.gap_checked) + ' (refreshed every 3 months; links won since then are removed). Common Crawl adds its monthly view.', true) : '') + (s.gap_error ? p_('DataForSEO gap not available: ' + esc(s.gap_error), true) : '') +
      table(['Site', 'Authority', 'Links to', 'Found by'], s.gap.slice(0, 20).map(g => [esc(g.domain), n(g.rank) + (g.cc_rank ? ' · CC #' + n(g.cc_rank) : ''), esc(g.links_to.join(', ')), esc({ dfs: 'DataForSEO', cc: 'Common Crawl', both: 'both' }[g.source] || g.source)]), s.competitors.length ? 'no gap found' : 'no competitors known yet — add them in the app (Settings → Tracking) or with Site Admin action "monitors"');
    html += h3('Unlinked mentions') + table(['Site', 'Page', 'Found by', ''], s.mentions.slice(0, 15).map(x => [esc(x.domain), link(x.url, x.title || x.url), esc({ news: 'news', web: 'web search', dfs_mention: 'DataForSEO' }[x.source] || x.source), x.verified ? 'checked: names you, no link' : 'not checked']), 'no pages found that name you without linking');
  }
  if (s.spammy.length) html += h3('Spammy new links') + table(['From', 'Spam', 'Anchor'], s.spammy.slice(0, 12).map(l => [esc(l.from_domain), n(l.spam), esc(l.anchor)])) + p_('Google ignores most spam links on its own. ' + (s.disavow_text ? 'A disavow list is attached for review: upload it only for a manual action or a paid-link pattern you did not create.' : ''), true);
  const drafts = pipe.filter(r => r.outreach_body && (r.status || 'new') === 'new').sort((a, b) => (Number(b.score) || 0) - (Number(a.score) || 0)).slice(0, 8);
  const follows = pipe.filter(r => r.status === 'contacted' && r.followup_body && String(r.followup_body).length > 10).slice(0, 8);
  const draftBox = (r, sub, body, tag) => '<div style="border:1px solid #e2e8f0;padding:8px 10px;margin:6px 0"><div style="font-size:12px;color:#64748b">' + esc(r.prospect_domain) + ' · ' + esc(tag) + (r.contact_email ? ' · to: ' + esc(r.contact_email) : '') + ' · ' + esc(r.detail) + '</div><div style="font-weight:600;font-size:13px;margin-top:4px">' + esc(sub) + '</div><pre style="white-space:pre-wrap;font-family:inherit;font-size:13px;margin:4px 0 0">' + esc(body) + '</pre></div>';
  if (full || drafts.length) html += h3('Outreach — this month\'s drafts') + (drafts.length ? drafts.map(r => draftBox(r, r.outreach_subject, r.outreach_body, (TYPE[r.type] || r.type) + ' · score ' + (r.score || 0))).join('') : p_('No new drafts this month.', true));
  if (follows.length) html += h3('Follow-ups due') + follows.map(r => draftBox(r, r.followup_subject, r.followup_body, 'follow-up ' + r.followup_step)).join('');
  if (full) html += h3('Prospect pipeline') + p_(esc(counts) + (won.length ? ' · <b>won this month: ' + esc(won.map(w => w.prospect_domain).join(', ')) + '</b>' : '')) + p_('Mark a prospect as contacted / won / rejected in the app (Backlinks → Outreach) or with Site Admin action "prospect". Contacted prospects get follow-up drafts after 7 and 14 days; "won" is set when the link is found on the page. Full list: prospects.csv.', true);
  html += h3('How this works') + p_('Every Monday the monitor checks for lost and new links and re-checks the valuable ones on their pages (alert e-mail only when something important happened); the first run of each month is the full report. Cost this run: $' + s.cost_usd.toFixed(2) + '.', true) +
    p_('Data: DataForSEO Backlinks; Bing Webmaster Tools; Google Search Console (your upload); Google Analytics 4; the <a href="https://commoncrawl.org/web-graphs" style="color:#1d4ed8">Common Crawl web graph</a>; Wikipedia; Hacker News (Algolia); news from the <a href="https://www.gdeltproject.org/" style="color:#1d4ed8">GDELT Project</a>' + (drCol ? '; <a href="https://ahrefs.com/" style="color:#1d4ed8">Domain Rating by Ahrefs</a>' : '') + '.', true) + '</div>';
  const csv = ['site,prospect_domain,type,status,score,authority,spam,detail,source_url,target_url,contact_email,first_seen,last_seen,won_at,outreach_subject,outreach_body,followup_subject,followup_body,note'].concat(pipe.map(r => [r.domain, r.prospect_domain, r.type, r.status, r.score, r.rank, r.spam_score, r.detail, r.source_url, r.target_url, r.contact_email, r.first_seen, r.last_seen, r.won_at, r.outreach_subject, r.outreach_body, r.followup_subject, r.followup_body, r.note].map(csvCell).join(','))).join('\n');
  const subject = (full ? '[Backlinks] ' : '[Backlink alert] ') + s.domain + ' — ' + n(C.union || S.referring_domains) + ' referring sites' + (s.important_lost.length ? ' · ' + s.important_lost.length + ' important link(s) lost' : '') + (s.spammy.length >= 3 ? ' · ' + s.spammy.length + ' spammy' : '') + (won.length ? ' · ' + won.length + ' won' : '');
  const file_name = 'backlinks-' + s.domain.replace(/[^a-z0-9]+/gi, '-') + '-' + s.checked_at.slice(0, 10) + '.html';
  const binary = { data: { data: b64(wrapDoc(subject, html)), mimeType: 'text/html', fileName: file_name, fileExtension: 'html' } };
  if (full && pipe.length) binary.prospects_csv = { data: b64(csv), mimeType: 'text/csv', fileName: 'prospects-' + s.domain.replace(/[^a-z0-9]+/gi, '-') + '.csv', fileExtension: 'csv' };
  if (s.disavow_text) binary.disavow_txt = { data: b64(s.disavow_text), mimeType: 'text/plain', fileName: 'disavow-candidates-' + s.domain.replace(/[^a-z0-9]+/gi, '-') + '.txt', fileExtension: 'txt' };
  const best = L.filter(r => r.status !== 'lost' && r.kind === 'web').sort((a, b) => b.seo_value - a.seo_value).slice(0, 25).map(r => ({ ref_domain: r.ref_domain, from_url: r.from_url, seo_value: r.seo_value, referral_value: r.referral_value, brand_value: r.brand_value, link_type: r.link_type, rel: r.rel, placement: r.placement, authority: r.authority, dr: r.dr, verify: r.verify, visits: r.visits, sources: r.sources }));
  return { json: { ...s, refdomains: undefined, ledger_rows: undefined, best, pipeline: { counts, won: won.map(w => w.prospect_domain), total: pipe.length }, prospects: pipe.slice(0, 60), subject, html, file_name, status: 'progress', stage: 'backlinks' }, binary };
});
