import { dirname, resolve } from 'node:path';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import { config } from '../config';
import * as schema from './schema';

export const sqlClient = postgres(config.databaseUrl, { max: 10, onnotice: () => {} });
export const db = drizzle(sqlClient, { schema });
export type Db = typeof db;

/** Applies the SQL migrations in server/drizzle (generated by `npm run db:generate`). */
export async function runMigrations(): Promise<void> {
  const here = dirname(fileURLToPath(import.meta.url));
  // src/db (tsx) or dist (bundled): the migrations folder sits next to package.json
  const candidates = [resolve(here, '../../drizzle'), resolve(here, '../drizzle'), resolve(process.cwd(), 'drizzle')];
  const folder = candidates.find((p) => existsSync(resolve(p, 'meta/_journal.json')));
  if (!folder) throw new Error('migrations folder not found (looked in ' + candidates.join(', ') + ')');
  await migrate(db, { migrationsFolder: folder });
}

export { schema };
