// Extra fixtures for the v5 methodology upgrade (discovery research pulls, facts search, critic, client pages).
const F = require('./fixtures');
const task = (result, extra = {}) => ({ version: '0.1.2026', status_code: 20000, status_message: 'Ok.', cost: 0.01, tasks: [{ id: 'x', status_code: 20000, status_message: 'Ok.', cost: 0.01, result: [result], ...extra }] });
const MODS = ['', ' services', ' company', ' cost', ' dubai', ' uae', ' for distributors', ' consultants', ' partner', ' pricing', ' vs sap', ' checklist', ' steps', ' software', ' best', ' meaning', ' jobs', ' course', ' salary', ' pdf'];
const hash = (s) => { let h = 7; for (const c of s) h = (h * 31 + c.charCodeAt(0)) % 100003; return h; };
const kwItem = (kw, i, withSerp = true) => {
  const h = hash(kw);
  const vol = [20, 40, 70, 110, 170, 260, 390, 590, 880, 1300, 1900, 2900][h % 12];
  const kd = h % 100 < 35 ? 10 + (h % 20) : 30 + (h % 55);
  const intent = /cost|pricing|quote|price/.test(kw) ? 'transactional' : /best|company|services|partner|consultants|vs|software/.test(kw) ? 'commercial' : /jobs|salary|course|pdf|meaning|login/.test(kw) ? 'informational' : 'informational';
  const types = ['organic', 'people_also_ask']; if (h % 3 === 0) types.push('ai_overview'); if (h % 5 === 0) types.push('featured_snippet'); if (h % 7 === 0) types.push('video'); if (/dubai|uae/.test(kw)) types.push('local_pack');
  return { se_type: 'google', keyword: kw, keyword_info: { search_volume: vol, cpc: +((h % 25) + 1.5).toFixed(2), competition: 0.4, competition_level: 'MEDIUM', monthly_searches: Array.from({ length: 12 }, (_, m) => ({ year: 2026, month: 12 - m, search_volume: vol })), search_volume_trend: { yearly: (h % 60) - 20, quarterly: 3 } },
    keyword_properties: { keyword_difficulty: kd, words_count: kw.split(' ').length, core_keyword: null }, search_intent_info: { main_intent: intent }, serp_info: withSerp ? { serp_item_types: types, se_results_count: 1000000 + h * 1000 } : undefined, avg_backlinks_info: { referring_domains: 20 + (h % 300) } };
};
const expand = (seed, n) => Array.from({ length: n }, (_, i) => (i % 4 === 0 ? MODS[i % MODS.length].trim() + ' ' + seed : seed + MODS[i % MODS.length]).replace(/\s+/g, ' ').trim());
const ideas = (seeds, n) => task({ seed_keywords: seeds, total_count: n, items_count: n, items: [...new Set(seeds.flatMap(s => expand(s, Math.ceil(n / seeds.length))))].slice(0, n).map((k, i) => kwItem(k, i)) });
const suggestions = (seed, n) => task({ seed_keyword: seed, items: expand(seed, n).map((k, i) => kwItem(k, i)) });
const related = (seed, n) => task({ seed_keyword: seed, items: expand(seed, n).map((k, i) => ({ se_type: 'google', keyword_data: kwItem(k, i), depth: 1, related_keywords: ['x', 'y'] })) });
const runResearch = (reqs) => reqs.map(r => r.kind === 'ideas' ? ideas(r.body[0].keywords, 120) : r.kind === 'suggestions' ? suggestions(r.body[0].keyword, 60) : r.kind === 'related' ? related(r.body[0].keyword, 40) : F.serpTop);
const runCompetitorKeywords = (reqs) => reqs.map((r, i) => r.kind === 'competitor' ? (i === 1 ? { tasks: [{ status_code: 40200, status_message: 'Payment Required.' }] } : F.ranked(r.domain)) : ideas(r.body[0].keywords, 50));
const relevance = (chunk) => ({ output: { items: chunk.keywords_chunk.map(k => { const kw = k.keyword; const bad = /jobs|salary|course|pdf|meaning|login/.test(kw); const adj = /checklist|steps|what is|meaning/.test(kw) && !bad; return { keyword: kw, relevance: bad ? 0 : adj ? 1 : 2, intent: k.intent, page_type: /cost|pricing/.test(kw) ? 'Landing Page' : /checklist|steps|what is/.test(kw) ? 'Guide' : /vs|best/.test(kw) ? 'Comparison Page' : 'Service Page', topic: kw.replace(/\b(dubai|uae|cost|pricing|best|company|services|partner|consultants|for distributors|software)\b/g, '').replace(/\s+/g, ' ').trim().split(' ').slice(0, 2).join(' ') || 'erp' }; }) } });
const aiDemand = (keywords) => task({ items: keywords.slice(0, 20).map((k, i) => ({ keyword: k, location_code: 2784, language_code: 'en', ai_search_volume: 50 + (hash(k) % 900), ai_monthly_searches: [] })) });
const factsSerp = task({ keyword: 'erp implementation services statistics 2026', items: [
  { type: 'organic', rank_group: 1, domain: 'www.statista.com', url: 'https://www.statista.com/statistics/erp-market', title: 'ERP software market size 2026', description: 'The global ERP software market is forecast to reach 78.4 billion U.S. dollars in 2026, growing 8.2 percent year on year.' },
  { type: 'organic', rank_group: 2, domain: 'www.gartner.com', url: 'https://www.gartner.com/en/erp-survey', title: 'Gartner ERP survey', description: 'Gartner finds 55 to 75 percent of ERP projects fail to meet their objectives, most often because of poor data migration planning.' },
  { type: 'organic', rank_group: 3, domain: 'erpblog.example.net', url: 'https://erpblog.example.net/stats', title: 'ERP stats', description: 'Our survey of 40 clients shows 3 month timelines are common.' },
  { type: 'organic', rank_group: 4, domain: 'www.mckinsey.com', url: 'https://www.mckinsey.com/erp-value', title: 'Capturing value from ERP', description: 'Companies that run a structured change programme report 20 to 30 percent higher ERP adoption after 12 months.' },
  { type: 'people_also_ask', items: [{ title: 'What percentage of ERP implementations fail?' }, { title: 'How long does ERP implementation take on average?' }] }
] });
const critique = { score: 68, verdict: 'revise', strengths: ['Clear structure that follows the outline', 'Quick answer is quotable'], problems: [
  { severity: 'high', location: 'Over 500 clients trust structured ERP implementation services', issue: 'Client count is invented and has no source', fix: 'Replace with [Number] or a client fact' },
  { severity: 'medium', location: 'Our Implementation Methodology', issue: 'Section is generic: no decision rule or example', fix: 'Add a worked example of a distributor go-live and the rule for phased vs big-bang' },
  { severity: 'low', location: 'We guarantee delivery on time', issue: 'Guarantee claim not in client facts', fix: 'Remove or make it a placeholder' }
], banned_phrases_found: ['seamless'], unsupported_claims: ['Over 500 clients', '30% of budgets go to data work'], missing_brief_items: ['information gain: phased vs big-bang decision rule'], revision_instructions: '1. Replace invented counts with placeholders. 2. Add the phased-vs-big-bang decision rule with an example. 3. Remove "seamless".' };
const briefV5 = { ...F.brief, image_suggestions: [{ placement: 'hero', purpose: 'hero', subject: 'Warehouse team using a tablet ERP in a UAE distribution centre', alt_text: 'ERP implementation for a UAE distributor: warehouse team checking stock on a tablet', caption: '', filename: 'erp-implementation-services-uae-hero.webp' }, { placement: 'How the implementation works', purpose: 'diagram', subject: 'Four-phase timeline: discovery, configuration, data migration, go-live', alt_text: 'ERP implementation phases from discovery to go-live', caption: 'The four phases of a fixed-scope ERP implementation', filename: 'erp-implementation-phases.webp' }, { placement: 'What it costs', purpose: 'chart', subject: 'Cost split between licences and services', alt_text: 'ERP implementation cost breakdown: licences versus services', caption: '', filename: 'erp-implementation-cost-breakdown.webp' }], title_variants: ['ERP Implementation Services UAE: Fixed-Scope Rollouts', 'UAE ERP Implementation Partner for Distributors'], meta_variants: ['Fixed-scope ERP implementation for UAE distributors. Odoo and Dynamics 365, bilingual consultants. Book a scoping call.'],
  audience_pain_points: ['projects overrun', 'data migration risk', 'staff adoption'], objections: ['Will it disrupt operations?', 'How much will it really cost?'], reading_level: 'busy operations manager, grade 9',
  information_gain: ['phased vs big-bang decision rule for distributors', 'data migration checklist with owner per step'], snippet_targets: [{ question: 'How much does ERP implementation cost in the UAE?', answer: 'ERP implementation in the UAE is usually priced as licences plus services. Services cover discovery, configuration, data migration, training and go-live support and typically cost more than licences in year one. Scope by department and migrate only clean data to control the total.' }],
  terms_to_use: [{ term: 'data migration', min_count: 3 }, { term: 'go-live', min_count: 2 }, { term: 'business central', min_count: 2 }, { term: 'training', min_count: 2 }, { term: 'inventory', min_count: 1 }, { term: 'implementation partner', min_count: 1 }],
  evidence_plan: [{ fact: 'Gartner finds 55 to 75 percent of ERP projects fail to meet their objectives, most often because of poor data migration planning.', source_url: 'https://www.gartner.com/en/erp-survey' }],
  client_facts: ['Northwind ERP implements Odoo and Dynamics 365 Business Central', 'Bilingual consultants', 'Serves distributors in the UAE'], proof_elements: ['[Customer review]', 'Microsoft partner status'], voice_rules: ['second person', 'no hype'] };
function draftV5(opts = {}) {
  let md = F.draft(opts);
  md = md.replace('## How Much Does ERP Implementation Cost in the UAE?\n\n', '## How Much Does ERP Implementation Cost in the UAE?\n\nERP implementation in the UAE is usually priced as licences plus services. Services cover discovery, configuration, data migration, training and go-live support and typically cost more than licences in year one. Scope by department and migrate only clean data to control the total. Gartner finds 55 to 75 percent of ERP projects fail to meet their objectives ([Gartner](https://www.gartner.com/en/erp-survey)).\n\n');
  md = md.replace('Our Implementation Methodology\n\n', 'Our Implementation Methodology\n\nWe deliver a seamless, robust rollout that will elevate your operations. Data migration and go-live for Business Central happen in phases, with training for the inventory team. ');
  return md;
}
// ---------- keyword ladder ----------
const rankedFor = (domain, kws) => task({ target: domain, items: kws.map((k, i) => ({ se_type: 'google', keyword_data: kwItem(k.keyword, i), ranked_serp_element: { serp_item: { type: 'organic', rank_group: k.position, rank_absolute: k.position, domain, url: 'https://' + domain + '/' + k.keyword.replace(/\s+/g, '-') + '/' } } })) });
const LMODS = [' software', ' software for small business', ' requirements', ' deadline', ' mandate', ' penalties', ' registration', ' format', ' xml format', ' phase 1', ' phase 2', ' peppol', ' peppol access point', ' accredited service providers', ' asp list', ' for freelancers', ' for sme', ' vat', ' fta', ' guide', ' checklist', ' how to', ' what is', ' benefits', ' cost', ' pricing', ' consultants', ' company', ' partner', ' implementation', ' integration', ' erp integration', ' tally', ' zoho', ' odoo', ' sap', ' quickbooks', ' dynamics 365', ' api', ' portal', ' login', ' training', ' course', ' jobs', ' salary', ' pdf', ' vs sap', ' best', ' top', ' dubai', ' abu dhabi', ' sharjah', ' free zone', ' b2b', ' b2g', ' b2c'];
const lexpand = (seed, n, offset = 0) => Array.from({ length: n }, (_, i) => { const m = LMODS[(i + offset) % LMODS.length]; return (i % 5 === 0 ? m.trim() + ' ' + seed : seed.replace(/ in uae$/, '') + m + (i % 3 === 0 ? ' uae' : '')).replace(/\s+/g, ' ').trim(); });
const lsuggestions = (seed, n) => task({ seed_keyword: seed, items: [...new Set(lexpand(seed, n, 0))].map((k, i) => kwItem(k, i)) });
const lrelated = (seed, n) => task({ seed_keyword: seed, items: [...new Set(lexpand(seed, n, 17))].map((k, i) => ({ se_type: 'google', keyword_data: kwItem(k, i), depth: 1, related_keywords: [] })) });
const lideas = (seeds, n) => task({ seed_keywords: seeds, items: [...new Set(seeds.flatMap((s, j) => lexpand(s, Math.ceil(n / seeds.length), 29 + j * 7)))].slice(0, n).map((k, i) => kwItem(k, i)) });
const ladderResearch = (reqs) => reqs.map(r => r.kind === 'suggestions' ? lsuggestions(r.body[0].keyword, 120) : r.kind === 'related' ? lrelated(r.body[0].keyword, 60) : r.kind === 'ideas' ? lideas(r.body[0].keywords, 150)
  : r.kind === 'ranked' ? rankedFor(r.domain, [{ keyword: 'e invoicing software uae', position: 14 }, { keyword: 'e invoicing in uae', position: 38 }, { keyword: 'erp implementation dubai', position: 9 }, { keyword: 'northwind erp login', position: 1 }]) : task({ items: [] }));
const ladderRelevance = (chunk) => ({ output: { items: chunk.keywords_chunk.map(k => { const kw = k.keyword; const bad = /jobs|salary|course|pdf|meaning|login/.test(kw); const adj = /checklist|steps|what is|meaning|vs sap/.test(kw) && !bad;
  return { keyword: kw, relevance: bad ? 0 : adj ? 1 : 2, intent: k.intent, page_type: /cost|pricing/.test(kw) ? 'Landing Page' : /checklist|steps|what is/.test(kw) ? 'Guide' : /vs|best/.test(kw) ? 'Comparison Page' : 'Service Page',
    topic: kw.replace(/\b(dubai|uae|cost|pricing|best|company|services|partner|consultants|for distributors|software|in)\b/g, '').replace(/\s+/g, ' ').trim().split(' ').slice(0, 2).join(' ') || 'e invoicing' }; }) } });
// tracker: a SERP with our domain at `position` (0 = absent)
const serpFor = (keyword, domain, position) => task({ keyword, items: [...Array.from({ length: 30 }, (_, i) => ({ type: 'organic', rank_group: i + 1, rank_absolute: i + 2, domain: i + 1 === position ? 'www.' + domain : 'site' + (i + 1) + '.example', url: i + 1 === position ? 'https://www.' + domain + '/' + keyword.replace(/\s+/g, '-') + '/' : 'https://site' + (i + 1) + '.example/p' })), { type: 'people_also_ask', items: [] }, { type: 'ai_overview', items: [] }] });
module.exports = { task, kwItem, ideas, suggestions, related, runResearch, runCompetitorKeywords, relevance, aiDemand, factsSerp, critique, briefV5, draftV5, rankedFor, ladderResearch, ladderRelevance, serpFor };
