// Fixtures for the backlink monitor v4.10 (every source merged + our own link check; BACKLINKS_SPEC.md). The site is techand.ai with its
// REAL DataForSEO data of 2026-10-02 (fixtures_live/bl_*.json: peppol.org reported LOST, five spam links reported NEW), the REAL peppol.org
// members page fetched 2026-10-08 (the link is there, followed, in the content: DataForSEO's "lost" was wrong), the REAL thedocmag.com page
// (the spam link is gone, the page redirects elsewhere) and the REAL GA4 referral reports of techand.ai. Bing, Wikipedia, Hacker News,
// GDELT, web search, Common Crawl rows, the Search Console upload and the other linking pages are built to exercise every path.
const fs = require('fs'); const path = require('path'); const zlib = require('zlib');
const L = (n) => JSON.parse(fs.readFileSync(path.join(__dirname, 'fixtures_live', n + '.json'), 'utf8'));
const page = (n) => zlib.gunzipSync(fs.readFileSync(path.join(__dirname, 'fixtures_live', n + '.html.gz'))).toString('utf8');
const clone = (o) => JSON.parse(JSON.stringify(o));
const SITE = 'site_techand-ai', DOMAIN = 'techand.ai';
const ok = (items, cost = 0.0242, extra = {}) => ({ tasks: [{ status_code: 20000, status_message: 'Ok.', cost, result: [{ items_count: items.length, items, ...extra }] }] });
const iso = (daysAgo) => new Date(Date.now() - daysAgo * 864e5).toISOString();
const dfsDate = (daysAgo) => iso(daysAgo).replace('T', ' ').slice(0, 19) + ' +00:00';
// ---- plan inputs ----
const sites = () => [{ json: { site_id: SITE, domain: DOMAIN, gsc_property: 'sc-domain:techand.ai', ga4_property_id: '543096312', country: 'United Arab Emirates', location_code: 2784, language_code: 'en', email: '', callback_url: 'http://server:4000/api/hooks/n8n/tok', keywords: 'e invoicing uae, peppol uae', status: 'active', source: 'app' } }];
const ladders = () => [{ json: { ladder_id: 'lad_t', domain: DOMAIN, head_keyword: 'e invoicing in uae', rung: 4, page_no: 5, keyword: 'e invoicing in uae', target_url: 'https://techand.ai/insights/e-invoicing-in-uae', page_exists: true, status: 'published' } }];
const monitors = (o = {}) => [{ json: { site_id: SITE, domain: DOMAIN, ai_visibility: true, ai_engines: '', ai_prompts_max: 8, backlinks: true, audit_monthly: true, audit_pages: 200, audit_js: false, competitors: 'complyance.io, cleartax.com', brand_names: 'Techand Systems', updated_at: iso(5), request_id: '', ...o } }];
const profiles = () => [{ json: { site_id: SITE, domain: DOMAIN, business_name: 'Techand Systems', business_type: 'ERP and e-invoicing consultancy', city: 'Dubai', country_code: 'AE' } }];
// ---- the ledger of the previous run (one valuable link that will be missed once, one missed once already that is now gone, one unchanged) ----
const ledgerPrev = () => [
  { site_id: SITE, domain: DOMAIN, ref_domain: 'oldsite-erp.net', kind: 'web', from_url: 'https://oldsite-erp.net/links', to_url: 'https://techand.ai/', anchor: 'Techand Systems', anchor_kind: 'brand', rel: 'follow', placement: 'content', link_type: 'resource', relevance: 0.67, note: 'ERP resources page', sources: 'dfs', source_count: 1, first_seen: '2026-05-01', last_seen: '2026-09-07', status: 'live', lost_at: '', lost_reason: '', miss_count: 0, verify: 'found', verified_at: iso(31), noindex: false, canonical_elsewhere: false, outbound: 12, page_title: 'ERP resources', context: '', authority: 210, dr: 0, cc_rank: 0, page_keywords: 30, spam_score: 2, original: true, sitewide: 1, links: 1, visits: 0, key_events: 0, ai_cited: false, seo_value: 52, referral_value: 0, brand_value: 40, updated_at: iso(31) },
  { site_id: SITE, domain: DOMAIN, ref_domain: 'gonepartner.com', kind: 'web', from_url: 'https://gonepartner.com/partners', to_url: 'https://techand.ai/', anchor: 'techand.ai', anchor_kind: 'url', rel: 'follow', placement: 'content', link_type: 'partner', relevance: 1, note: 'Partner page', sources: 'dfs,bing', source_count: 2, first_seen: '2026-03-01', last_seen: '2026-09-01', status: 'at_risk', lost_at: '', lost_reason: '', miss_count: 1, verify: 'missing', verified_at: iso(7), noindex: false, canonical_elsewhere: false, outbound: 20, page_title: 'Our partners', context: '', authority: 260, dr: 31, cc_rank: 0, page_keywords: 12, spam_score: 1, original: true, sitewide: 1, links: 1, visits: 4, key_events: 0, ai_cited: false, seo_value: 55, referral_value: 13, brand_value: 41, updated_at: iso(7) },
  { site_id: SITE, domain: DOMAIN, ref_domain: 'stablevendors.org', kind: 'web', from_url: 'https://stablevendors.org/vendors', to_url: 'https://techand.ai/', anchor: 'Techand', anchor_kind: 'brand', rel: 'follow', placement: 'content', link_type: 'listing', relevance: 0.67, note: '', sources: 'dfs', source_count: 1, first_seen: '2026-04-01', last_seen: '2026-09-07', status: 'live', lost_at: '', lost_reason: '', miss_count: 0, verify: 'found', verified_at: iso(10), noindex: false, canonical_elsewhere: false, outbound: 8, page_title: 'Vendors', context: '', authority: 0, dr: 0, cc_rank: 0, page_keywords: 0, spam_score: 0, original: true, sitewide: 0, links: 0, visits: 0, key_events: 0, ai_cited: false, seo_value: 30, referral_value: 0, brand_value: 35, updated_at: iso(3) }];
const prospectsPrev = () => [
  { site_id: SITE, domain: DOMAIN, prospect_domain: 'mof.gov.ae', type: 'ai_source', rank: 0, spam_score: 0, detail: 'Cited 3x in AI answers', status: 'new', first_seen: iso(20), last_seen: iso(20), outreach_body: '' },
  { site_id: SITE, domain: DOMAIN, prospect_domain: 'peppolnews.com', type: 'gap', rank: 180, spam_score: 0, detail: 'Links to complyance.io, not to you', source_url: '', target_url: 'https://techand.ai/', status: 'contacted', first_seen: iso(40), last_seen: iso(40), won_at: '', outreach_subject: 'A UAE Peppol guide for your readers', outreach_body: 'Hello, ...', note: '', score: 30, origin: 'dfs', contact_email: 'editor@peppolnews.com', contact_url: '', contacted_at: iso(9), followup_step: 0, followup_subject: '', followup_body: '', verified_at: '' },
  { site_id: SITE, domain: DOMAIN, prospect_domain: 'erpnews.ae', type: 'gap', rank: 280, spam_score: 0, detail: 'Links to cleartax.com, not to you', source_url: '', target_url: 'https://techand.ai/', status: 'contacted', first_seen: iso(60), last_seen: iso(60), won_at: '', outreach_subject: 's', outreach_body: 'b', note: 'pitched the guide', score: 35, origin: 'dfs', contact_email: '', contact_url: '', contacted_at: iso(20), followup_step: 1, followup_subject: 'Re: s', followup_body: 'f', verified_at: '' }];
// Search Console upload (the app writes these rows) and the Common Crawl job's rows
const imports = () => [
  { site_id: SITE, domain: DOMAIN, import_id: 'imp_1', source: 'gsc_latest', ref_domain: 'peppol.org', from_url: 'https://peppol.org/members/full-members-list/', to_url: '', anchor: '', links: 0, last_crawled: '2026-09-28', imported_at: iso(2) },
  { site_id: SITE, domain: DOMAIN, import_id: 'imp_1', source: 'gsc_latest', ref_domain: 'partnerdir.ae', from_url: 'https://www.partnerdir.ae/uae/techand', to_url: '', anchor: '', links: 0, last_crawled: '2026-09-21', imported_at: iso(2) },
  { site_id: SITE, domain: DOMAIN, import_id: 'imp_1', source: 'gsc_latest', ref_domain: 'oldsite-erp.net', from_url: 'https://oldsite-erp.net/links', to_url: '', anchor: '', links: 0, last_crawled: '2026-08-02', imported_at: iso(2) },
  { site_id: SITE, domain: DOMAIN, import_id: 'imp_2', source: 'gsc_sites', ref_domain: 'uaedirectory.biz', from_url: '', to_url: '', anchor: '', links: 3, last_crawled: '', imported_at: iso(2) },
  { site_id: SITE, domain: DOMAIN, import_id: 'imp_0', source: 'gsc_latest', ref_domain: 'old-upload.com', from_url: 'https://old-upload.com/x', to_url: '', anchor: '', links: 0, last_crawled: '2026-01-01', imported_at: iso(90) }];
const graph = () => [
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'link', ref_domain: 'peppol.org', hc_pos: 52000, pr_pos: 61000, n_hosts: 3, links_to: '', checked_at: iso(6) },
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'link', ref_domain: 'partnerdir.ae', hc_pos: 2100000, pr_pos: 2500000, n_hosts: 1, links_to: '', checked_at: iso(6) },
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'link', ref_domain: 'ccpage.org', hc_pos: 900000, pr_pos: 1100000, n_hosts: 1, links_to: '', checked_at: iso(6) },
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'gap', ref_domain: 'einvoicingnews.com', hc_pos: 400000, pr_pos: 500000, n_hosts: 2, links_to: 'complyance.io,cleartax.com', checked_at: iso(6) },
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'gap', ref_domain: 'peppol.org', hc_pos: 52000, pr_pos: 61000, n_hosts: 3, links_to: 'complyance.io', checked_at: iso(6) },
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'gap', ref_domain: 'stripe.com', hc_pos: 64, pr_pos: 50, n_hosts: 40, links_to: 'cleartax.com', checked_at: iso(6) },   // live 2026-10-08: a household name
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'gap', ref_domain: 'cleartax.in', hc_pos: 900, pr_pos: 800, n_hosts: 5, links_to: 'cleartax.com', checked_at: iso(6) },   // the competitor's sister domain
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'gap', ref_domain: 'amazonaws.com', hc_pos: 36, pr_pos: 20, n_hosts: 9000, links_to: 'complyance.io', checked_at: iso(6) },   // live 2026-10-08: infrastructure in the graph
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'gap', ref_domain: 'blogspot.com', hc_pos: 40, pr_pos: 30, n_hosts: 9000, links_to: 'cleartax.com', checked_at: iso(6) },
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'gap', ref_domain: 'prnewswire.co.uk', hc_pos: 3000, pr_pos: 2500, n_hosts: 4, links_to: 'complyance.io', checked_at: iso(6) },   // live 2026-10-08: a press-release wire
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'gap', ref_domain: 'taxhub.ae', hc_pos: 900000, pr_pos: 900000, n_hosts: 1, links_to: 'cleartax.com', checked_at: iso(6) },   // local (.ae) vs
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jul-aug-sep', kind: 'gap', ref_domain: 'taxhub-global.com', hc_pos: 900000, pr_pos: 900000, n_hosts: 1, links_to: 'cleartax.com', checked_at: iso(6) },   // the same site elsewhere
  { site_id: SITE, domain: DOMAIN, release: 'cc-main-2026-jun-jul-aug', kind: 'link', ref_domain: 'older-release.com', hc_pos: 10, pr_pos: 10, n_hosts: 1, links_to: '', checked_at: iso(40) }];
// ---- DataForSEO (real lost / new / summary / refdomains / timeseries; the rest in the documented shapes) ----
const linkItem = (o) => ({ type: 'backlink', domain_from: o.domain, url_from: o.url, domain_to: DOMAIN, url_to: o.to || 'https://techand.ai/', dofollow: o.dofollow !== false, attributes: o.attributes || null, backlink_spam_score: o.spam || 0, domain_from_rank: o.rank || 100, page_from_rank: o.prank || 50,
  page_from_external_links: o.out || 10, page_from_title: o.title || '', first_seen: o.first || dfsDate(200), last_seen: o.last || dfsDate(5), anchor: o.anchor || 'Techand Systems', alt: null, semantic_location: o.sem ?? 'article', original: o.original !== false, links_count: 1, group_count: 1,
  ranked_keywords_info: { page_from_keywords_count_top_3: 0, page_from_keywords_count_top_10: 2, page_from_keywords_count_top_100: o.kw || 0 }, is_broken: false, url_to_status_code: 200 });
const links = () => ok([...clone(L('bl_new')).tasks[0].result[0].items, linkItem({ domain: 'erpnews.ae', url: 'https://erpnews.ae/2026/09/peppol-uae-explained', rank: 280, kw: 40, title: 'Peppol in the UAE, explained', anchor: 'Techand Systems’ Peppol guide', to: 'https://techand.ai/insights/e-invoicing-in-uae' }),
  linkItem({ domain: 'stablevendors.org', url: 'https://stablevendors.org/vendors', rank: 0, title: 'Vendors' }), linkItem({ domain: 'jsapp.io', url: 'https://jsapp.io/partners', rank: 330, title: 'Partners', sem: '' })]);
const anchors = () => ok([{ type: 'backlinks_anchor', anchor: 'techand.ai', referring_domains: 4, backlinks: 9 }, { type: 'backlinks_anchor', anchor: 'Techand Systems', referring_domains: 3, backlinks: 3 }, { type: 'backlinks_anchor', anchor: 'best casino bonus', referring_domains: 2, backlinks: 2 }, { type: 'backlinks_anchor', anchor: 'here', referring_domains: 1, backlinks: 1 }]);
const pages = () => ok([{ type: 'backlinks_domain_page', page: 'https://techand.ai/', status_code: 200, page_summary: { referring_domains: 6, backlinks: 12 } }, { type: 'backlinks_domain_page', page: 'https://techand.ai/insights/old-peppol-guide', status_code: 200, page_summary: { referring_domains: 2, backlinks: 2 } }]);
const compNew = (comp) => ok(comp === 'complyance.io' ? [linkItem({ domain: 'fintechnews.ae', url: 'https://fintechnews.ae/uae-e-invoicing-vendors', rank: 240, title: 'UAE e-invoicing vendors compared', first: dfsDate(12) }), linkItem({ domain: 'spamfarm.xyz', url: 'https://spamfarm.xyz/a', rank: 90, spam: 70 })]
  : [linkItem({ domain: 'erpnews.ae', url: 'https://erpnews.ae/2026/09/cleartax', rank: 280 })]);
const broken = () => ok([]);
const mentionsCA = () => ok([{ type: 'content_analysis_search', url: 'https://bizdaily.ae/erp-firms', domain: 'bizdaily.ae', domain_rank: 150, spam_score: 0, content_info: { title: 'ERP firms in Dubai', snippet: 'Techand Systems was named among ...' } }]);
const blFor = (req) => ({ summary: () => clone(L('bl_summary')), lost: () => clone(L('bl_lost')), new: () => clone(L('bl_new')), broken, refdomains: () => clone(L('bl_refdom')), links, anchors, pages, timeseries: () => clone(L('bl_ts')), mentions: mentionsCA, comp_new: () => compNew(req.competitor) }[req.kind] || (() => ok([])))();
const gapResp = () => ok([{ domain_intersection: { '1': { target: 'peppolnews.com', rank: 180, backlinks_spam_score: 0, backlinks: 3 } } }, { domain_intersection: { '1': { target: 'erpnews.ae', rank: 280, backlinks_spam_score: 0, backlinks: 2 }, '2': { target: 'erpnews.ae', rank: 280, backlinks: 1 } } }]);
const ranksFor = (targets) => ok(targets.map(t => ({ target: t, rank: { 'peppol.org': 598, 'partnerdir.ae': 140, 'ccpage.org': 120, 'zawya-press.com': 520, 'gulfbiz.ae': 260, 'bestof-software.com': 300, 'einvoicingnews.com': 200, 'uaedirectory.biz': 60 }[t] || 50 })), 0.0203);
const spamFor = (targets) => ok(targets.map(t => ({ type: 'backlinks_bulk_spam_score', target: t, spam_score: t === 'uaedirectory.biz' ? 35 : 3 })), 0.0203);
const drFor = (targets) => ({ domain_rating: { license: 'http://ahrefs.com/legal/domain-rating-license', targets: targets.map(t => ({ target: t + '/', domain_rating: { 'peppol.org': 77, 'erpnews.ae': 41, 'zawya-press.com': 78, 'techand.ai': 2.8 }[t] ?? 12 })) } });   // live shape 2026-10-08: 'domain/' + decimals
// ---- free sources ----
const wiki = () => ({ batchcomplete: true, query: { exturlusage: [{ pageid: 1, ns: 0, title: 'E-invoicing in the United Arab Emirates', url: 'https://techand.ai/insights/e-invoicing-in-uae' }, { pageid: 2, ns: 3, title: 'User talk:Someone', url: 'https://techand.ai/' }] } });
const hn = () => ({ hits: [{ objectID: '4111', title: 'Show HN: a free Peppol UAE invoice validator', url: 'https://techand.ai/tools/peppol-validator', created_at: '2026-08-01T10:00:00Z' }, { objectID: '4112', title: 'unrelated', url: 'https://www.techand.ai.example.net/x', created_at: '2026-08-02T10:00:00Z' }] });
const searxMention = () => ({ results: [{ url: 'https://gulfbiz.ae/uae-einvoicing-providers', title: 'UAE e-invoicing providers' }, { url: 'https://www.linkedin.com/posts/techand' }, { url: 'https://techand.ai/about' }, { url: 'https://conf.example.org/2022/program-book.pdf', title: '[PDF] Program book' }, { url: 'https://complyance.io/blog/techand-review', title: 'Techand review' }, { url: 'https://www.whois.com/whois/techand.ai', title: 'techand.ai WHOIS' }] });   // live 2026-10-08: a 16 MB PDF and competitors' pages came back
const searxList = () => ({ results: [{ url: 'https://bestof-software.com/best-e-invoicing-software-uae', title: 'Best e-invoicing software in UAE (2026)' }, { url: 'https://www.cleartax.com/ae/e-invoicing-service-providers-uae', title: 'Top e-invoicing service providers' }, { url: 'https://faqsite.ae/uae-e-invoicing-faqs/', title: 'UAE e-invoicing FAQs' }] });
const gdelt = () => ({ articles: [{ url: 'https://zawya-press.com/en/press-release/techand-systems-peppol', url_mobile: '', title: 'Techand Systems becomes an accredited Peppol service provider', seendate: '20260920T101500Z', socialimage: '', domain: 'zawya-press.com', language: 'English', sourcecountry: 'United Arab Emirates' }] });
const sourceFor = (req) => req.kind === 'wiki' ? wiki() : req.kind === 'hn' ? hn() : req.kind === 'searx_list' ? searxList() : searxMention();
const bingSites = () => ({ d: [{ __type: 'Site:#Microsoft.Bing.Webmaster.Api', Url: 'https://techand.ai/', IsVerified: true }, { Url: 'https://other.example.com/', IsVerified: true }] });
const bingCounts = (pageNo) => ({ d: { __type: 'LinkCounts:#Microsoft.Bing.Webmaster.Api', Links: pageNo ? [] : [{ Count: 3, Url: 'https://techand.ai/' }, { Count: 1, Url: 'https://techand.ai/insights/old-peppol-guide' }], TotalPages: 1 } });
const bingLinks = (link) => ({ d: { __type: 'LinkDetails:#Microsoft.Bing.Webmaster.Api', Details: /old-peppol/.test(link) ? [{ AnchorText: 'Peppol guide', Url: 'https://peppolblog.org/peppol-resources' }] : [{ AnchorText: 'Techand Systems', Url: 'https://www.partnerdir.ae/uae/techand' }, { AnchorText: 'techand.ai', Url: 'https://peppol.org/members/full-members-list/' }, { AnchorText: 'partner', Url: 'https://gonepartner.com/partners' }], TotalPages: 1 } });
const ga4 = () => L('ga4_referrals_techand');
const locateFor = (ref) => ref === 'ccpage.org' ? { results: [{ url: 'https://ccpage.org/resources/einvoicing', title: 'E-invoicing resources' }, { url: 'https://elsewhere.example.com/x' }] } : { results: [] };
// ---- linking pages (what *Fetch Linking Pages* returns: full response, text) ----
const html = (body, head = '') => '<!doctype html><html lang="en"><head><title>' + (head || 'Page') + '</title></head><body>' + body + '</body></html>';
const pg = (body, status = 200, headers = {}) => ({ statusCode: status, headers: { 'content-type': 'text/html', ...headers }, body });
const PAGES = {
  'https://peppol.org/members/full-members-list/': () => pg(page('page_peppol_members')),
  'https://www.partnerdir.ae/uae/techand': () => pg(html('<header class="site-header"><nav><a href="/">Home</a></nav></header><main><article class="entry"><h1>Techand Systems</h1><p>UAE ERP consultancy. <a href="https://techand.ai/" rel="nofollow ugc">Visit website</a></p></article></main>', 'Techand Systems — Partner directory')),
  'https://oldsite-erp.net/links': () => pg(html('<main><article><h1>ERP resources</h1><p>We moved our resources. <a href="https://other.example.com/">Other</a></p></article></main>', 'ERP resources')),
  'https://gonepartner.com/partners': () => pg('<html><body>Not found</body></html>', 404),
  'https://erpnews.ae/2026/09/peppol-uae-explained': () => pg(html('<main><article class="post"><h1>Peppol in the UAE, explained</h1><p>For a practical walk-through, see <a href="https://techand.ai/insights/e-invoicing-in-uae">Techand Systems’ Peppol guide</a>, which covers the 2027 deadline.</p></article><aside class="sidebar"><a href="https://ads.example.com">ad</a></aside></main>', 'Peppol in the UAE, explained — ERP News')),
  'https://stablevendors.org/vendors': () => pg(html('<main><ul><li><a href="https://techand.ai/">Techand</a></li></ul></main>', 'Vendors')),
  'https://jsapp.io/partners': () => pg('<html><head><title>Partners</title></head><body><div id="root"></div><script src="/app.js"></script></body></html>'),
  'https://ccpage.org/resources/einvoicing': () => pg(html('<main><article><h1>E-invoicing resources</h1><p>Guides.</p></article></main><aside class="widget-area"><section class="widget widget_text"><a href="https://techand.ai/">Techand Systems</a></section></aside>', 'E-invoicing resources')),
  'https://thedocmag.com/all/2835/13.html': () => pg(page('page_thedocmag')),
  'https://onvaxs.com/all/2835/13.html': () => ({ error: { message: 'getaddrinfo ENOTFOUND onvaxs.com' } }),
  'https://betulcrime.com/all/2835/13.html': () => pg('<html><head><title>Just a moment...</title></head><body><div id="challenge-platform"></div></body></html>', 403),
  'https://quotesblom.com/all/2835/13.html': () => pg('<html><body>gone</body></html>', 410),
  'https://www.betwinnermirror.com/all/2835/13.html': () => ({ error: { message: 'getaddrinfo ENOTFOUND www.betwinnermirror.com' } }),
  'https://robuta.com/?q=business+impact': () => ({ error: { message: 'getaddrinfo ENOTFOUND robuta.com' } }),
  // mention pages
  'https://gulfbiz.ae/uae-einvoicing-providers': () => pg(html('<main><article><h1>UAE e-invoicing providers</h1><p>Accredited providers include ClearTax, Complyance and Techand Systems, a Dubai consultancy.</p></article></main>', 'UAE e-invoicing providers')),
  'https://zawya-press.com/en/press-release/techand-systems-peppol': () => pg(html('<main><article class="story"><h1>Techand Systems becomes an accredited Peppol service provider</h1><p>Dubai — <a href="https://techand.ai/">Techand Systems</a> announced ...</p></article></main>', 'Techand Systems becomes an accredited Peppol service provider')),
  'https://bizdaily.ae/erp-firms': () => pg(html('<main><article><p>Firms such as Techand Systems and others.</p></article></main>', 'ERP firms in Dubai')),
  // list page
  'https://bestof-software.com/best-e-invoicing-software-uae': () => pg(html('<main><article><h1>Best e-invoicing software in UAE (2026)</h1><ol><li><a href="https://complyance.io/">Complyance</a></li><li>ClearTax — popular in India and the UAE</li></ol></article></main>', 'Best e-invoicing software in UAE (2026)')),
  // own pages
  'https://techand.ai/': () => pg(html('<main>home</main>')),
  'https://techand.ai/insights/old-peppol-guide': () => pg('<html><body>404</body></html>', 404),
  'https://techand.ai/insights/e-invoicing-in-uae': () => pg(html('<main>guide</main>')),
};
const pageFor = (url) => (PAGES[url] || (() => pg(html('<main><p>nothing about the site</p></main>'))))();
const rendered = () => ({ data: html('<main><section class="partners"><a href="https://techand.ai/">Techand Systems</a></section></main>', 'Partners') });
const contactPage = (url) => /gulfbiz/.test(url) && /contact/.test(url) ? pg(html('<main><p>Write to our editor: <a href="mailto:editor@gulfbiz.ae">editor@gulfbiz.ae</a> or noreply@gulfbiz.ae</p></main>')) : /bestof/.test(url) ? pg(html('<footer>Contact: hello@bestof-software.com</footer>')) : pg('<html><body>nothing</body></html>', 404);
const analyst = (job) => ({ output: { links: job.ids.map((d, i) => ({ n: i + 1, type: { 'peppol.org': 'partner', 'erpnews.ae': 'editorial', 'zawya-press.com': 'press', 'ccpage.org': 'resource', 'partnerdir.ae': 'directory', 'jsapp.io': 'partner' }[d] || 'other', relevance: { 'peppol.org': 3, 'erpnews.ae': 3, 'zawya-press.com': 3 }[d] ?? 2, note: 'note for ' + d })) } });
const writer = (job) => ({ output: { drafts: job.prospects.map(p => p.type === 'followup' ? { prospect_domain: p.prospect_domain, followup: p.step, subject: 'Re: ' + (p.first_subject || ''), body: 'Just checking whether you saw my note about the UAE Peppol guide. [Your name], Techand Systems' } : { prospect_domain: p.prospect_domain, followup: 0, subject: 'About ' + p.prospect_domain, body: 'Hello, ' + p.detail + ' [Your name], Techand Systems' }) } });
module.exports = { L, SITE, DOMAIN, sites, ladders, monitors, profiles, ledgerPrev, prospectsPrev, imports, graph, blFor, gapResp, ranksFor, spamFor, drFor, sourceFor, gdelt, bingSites, bingCounts, bingLinks, ga4, locateFor, pageFor, rendered, contactPage, analyst, writer, iso };
