// Weekly AI-visibility report per site (e-mail HTML + the same document for the PDF): headline, KPI tiles with last week's change, alerts,
// actions (with ready-to-send API bodies for content gaps), the answer grid (question x engine), competitors' share, the sources AI trusts,
// your cited pages, the monthly market view and the method. Uses the Claude brief when present, the computed facts otherwise.
/*__REPORT_KIT__*/
const metrics = $('AI Metrics').all().map(i => i.json);
let briefs = []; try { briefs = $('AI Brief').all().map(i => (i.json && i.json.output && typeof i.json.output === 'object') ? i.json.output : null); } catch (e) { briefs = []; }
const SYM = { cited: '<b style="color:#15803d">✓ cited</b>', mentioned: '<span style="color:#15803d">✓ named</span>', absent: '<span style="color:#b91c1c">✗</span>', none: '<span style="color:#94a3b8">no AI answer</span>', error: '<span style="color:#94a3b8">error</span>' };
return metrics.map((m, i) => {
  const b = briefs[i] || null; const M = m.metrics; const d = M.delta || {};
  const engs = Object.keys(m.engines);
  let html = '<div style="font-family:Segoe UI,Helvetica,Arial,sans-serif;color:#0f172a;max-width:900px">';
  html += '<h2 style="margin:0 0 2px;font-size:20px">AI search visibility: ' + esc(m.domain) + '</h2>' + p_(esc(m.checked_at.slice(0, 10)) + ' · ' + m.questions.length + ' buyer questions × ' + engs.length + ' AI engines' + (m.on_demand ? ' · on-demand run' : '') + (m.previous ? ' · compared with ' + esc(String(m.previous.checked_at).slice(0, 10)) : ' · first run (baseline)'), true);
  html += briefBox(b) + alertBox(m.alerts);
  html += '<table style="border-collapse:collapse;margin:8px 0"><tr>' + tile('Mentioned in', M.mention_rate + '%', m.previous ? dpts(d.mention_rate) : 'of ' + M.answered + ' AI answers') + tile('Your pages cited', M.citation_rate + '%', m.previous ? dpts(d.citation_rate) : M.cited + ' answers') +
    tile('Share of voice', M.share_of_voice + '%', m.previous ? dpts(d.share_of_voice) : 'vs ' + m.competitors.length + ' competitors') + tile('Avg. position', M.avg_rank ? '#' + M.avg_rank : '—', 'when named') + tile('AI Overview', M.aio_presence + '%', 'of searches show one; you cited in ' + M.aio_citation_rate + '%') + (M.brand && M.brand.answered ? tile('Brand recognised', M.brand.known + ' of ' + M.brand.answered, 'assistants know who you are', M.brand_known === false ? '#b91c1c' : '#15803d') : '') + '</tr></table>';
  const acts = (b && Array.isArray(b.actions) && b.actions.length) ? b.actions.map(a => ({ action: a.action, why: a.why })) : m.actions;
  html += h3('Do this next') + (acts.length ? '<ol style="margin:4px 0 4px 18px;padding:0;font-size:13px">' + acts.map(a => '<li style="margin:3px 0"><b>' + esc(a.action) + '</b> — ' + esc(a.why) + '</li>').join('') + '</ol>' : p_('Nothing urgent.', true));
  const gapActs = m.actions.filter(a => a.api_body);
  if (gapActs.length) html += p_('Write the missing pages with one call each (or use the form: <a href="' + esc(m.form_url) + '">' + esc(m.form_url) + '</a>):', true) + gapActs.map(a => '<pre style="background:#f1f5f9;padding:6px;font-size:11px;white-space:pre-wrap">POST ' + esc(m.api_url) + '\n' + esc(JSON.stringify(a.api_body)) + '</pre>').join('');
  html += h3('Answer by answer') + table(['Question', ...engs.map(e => m.engines[e].name)], m.questions.map(q => [esc(q.prompt) + '<br><span style="color:#64748b;font-size:11px">' + esc(q.kind) + (q.competitors.length && !q.won ? ' · named instead: ' + esc(q.competitors.slice(0, 3).join(', ')) : '') + '</span>', ...engs.map(e => SYM[q.engines[e]] || '—')]), 'no answers this week');
  html += h3('By engine') + table(['Engine', 'Answers', 'Named you', 'Cited your pages', 'Failed'], engs.map(e => { const x = m.engines[e]; return [esc(x.name), n(x.answered), x.mentioned + ' (' + x.mention_rate + '%)', x.cited + ' (' + x.citation_rate + '%)', n(x.errors)]; }));
  html += h3('Who AI recommends instead') + table(['Business', 'Answers naming it', 'Share of voice', ''], [['<b>' + esc(m.domain) + ' (you)</b>', n(M.mentioned), M.share_of_voice + '%', ''], ...m.competitors.map(c => [esc(c.domain), n(c.mentions), c.share + '%', c.auto ? 'detected' : 'your competitor'])], 'no other businesses named');
  html += h3('Sources AI relies on (where to get featured)') + table(['Source', 'Citations', 'Engines', 'Topics', 'Kind'], m.sources.map(s => [esc(s.domain), n(s.citations), esc(s.engines.join(', ')), esc(s.topics.join(', ')), esc({ official: 'official', platform: 'platform', media: 'news / media', directory: 'directory / reviews', authority: 'consultancy / research', site: 'site (PR target)' }[s.kind] || s.kind)]), 'no sources cited') + p_('These also appear in your link-prospect list (type ai_source); the Backlink Monitor drafts outreach for them.', true);
  html += h3('Your pages AI cites') + table(['Page', 'Citations'], m.our_pages.map(x => [link(x.url), n(x.citations)]), 'none yet');
  if (m.market) html += h3('Market view: who AI cites for "' + m.market.keyword + '"' + (m.market.carried ? ' (from ' + m.market.checked_at + ')' : '')) + (m.market.error ? p_('Not available: ' + esc(m.market.error), true) : p_((m.market.total_mentions ? n(m.market.total_mentions) + ' AI answers in the DataForSEO index (Google AI Overview and ChatGPT) mention this topic. ' : '') + (m.market.you ? 'You are #' + m.market.you + ' of the cited domains.' : 'Your domain is not among the cited domains yet.')) + table(['Domain', 'Mentions', 'AI search volume'], (m.market.top || []).slice(0, 10).map(x => [esc(x.domain), n(x.mentions), n(x.ai_search_volume)])));
  html += h3('How this is measured') + p_('Every Monday the same buyer questions are asked to ChatGPT (the real chatgpt.com answer), Perplexity, Gemini and Claude with web search, and to Google AI Mode; the matching Google search is checked for an AI Overview. Rates and share of voice use the buyer questions only; the question about the brand itself measures recognition. "Named" = the answer mentions ' + esc(m.brand_names.join(' / ')) + '; "cited" = it links one of your pages; share of voice = your mentions against the competitors\' mentions; position = your place among the businesses an answer names. Answers vary between runs, so read the trend over several weeks. Cost this run: $' + m.cost_usd.toFixed(2) + ' (DataForSEO).', true);
  html += '</div>';
  const subject = '[AI visibility] ' + m.domain + ' — named in ' + M.mention_rate + '% of AI answers' + (m.previous && d.mention_rate ? ' (' + (d.mention_rate > 0 ? '+' : '') + d.mention_rate + ' pts)' : '') + (m.alerts.length ? ' · ' + m.alerts.length + ' alert(s)' : '');
  const file_name = 'ai-visibility-' + m.domain.replace(/[^a-z0-9]+/gi, '-') + '-' + m.checked_at.slice(0, 10) + '.html';
  return { json: { ...m, brief: b, subject, html, file_name, status: 'progress', stage: 'ai_visibility' }, binary: { data: { data: b64(wrapDoc(subject, html)), mimeType: 'text/html', fileName: file_name, fileExtension: 'html' } } };
});
