// Who to tell about an urgent notice: the site's e-mail / callback from seo_sites, the ladder's as fallback.
const a = $('Classify Notification').first().json;
const rowsOf = (name) => { try { return $(name).all().map(i => i.json).filter(r => r && typeof r === 'object' && !r.error); } catch (e) { return []; } };
const normD = (x) => String(x || '').toLowerCase().trim().replace(/^https?:\/\//, '').replace(/^www\./, '').replace(/[\/?#].*$/, '');
const site = rowsOf('Load Sites (Alerts)').find(s => normD(s.domain) === a.domain) || {}; const lad = rowsOf('Load Ladders (Alerts)').find(l => normD(l.domain) === a.domain) || {};
const esc = (x) => String(x == null ? '' : x).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const what = a.kind === 'manual_action' ? 'Google has applied a <b>manual action</b> to the site. Rankings are suppressed until it is fixed and a review is requested.' : 'Google reports a <b>security issue</b> on the site (hacked content, malware or deceptive pages). Visitors see warnings and rankings drop until it is cleaned.';
const steps = a.kind === 'manual_action' ? ['Open Search Console → Security &amp; Manual Actions → Manual actions and read the exact reason and the affected pages.', 'Fix every page it names (remove spam, unnatural links, thin or cloaked content) across the whole site, not only the examples.', 'Click Request review and describe what was fixed; reviews take days to weeks.'] : ['Open Search Console → Security issues for the details and the sample URLs.', 'Clean the site: remove malware / injected content, update the CMS and plugins, change all passwords, check file integrity.', 'Request a review in Search Console once clean; the warning stays until Google re-checks.'];
const html = '<p><b>Urgent Search Console notice for ' + esc(a.domain) + '</b></p><p>' + what + '</p><p><i>' + esc(a.subject) + '</i> (received ' + esc(a.received_at.slice(0, 16).replace('T', ' ')) + ' UTC)</p><p>' + esc(a.summary.slice(0, 300)) + '</p><ol>' + steps.map(x => '<li>' + x + '</li>').join('') + '</ol><p>The Monday report keeps this notice until Search Console confirms it is resolved; reply to this e-mail if you need help with the fix.</p>';
return [{ json: { ...a, email: site.email || lad.email || '', callback_url: site.callback_url || lad.callback_url || '', subject_line: '[URGENT] Search Console: ' + (a.kind === 'manual_action' ? 'manual action' : 'security issue') + ' on ' + a.domain, html, stage: 'console_alert', status: 'alert' } }];
