// Compact facts for the AI brief (one item per site): totals, movers, opportunities, tracked keywords, pages, traffic, trends, alerts, actions.
const r1 = (v) => Math.round((Number(v) || 0) * 10) / 10;
return $('Site Metrics').all().map(i => { const m = i.json; const G = m.gsc, A = m.ga4;
  const facts = { domain: m.domain, period: m.period.current, previous_period: m.period.previous, weeks_tracked: m.weeks_tracked,
    search_console: G.connected ? { totals: G.totals, deltas: G.deltas, queries_with_impressions: G.query_count, winners: G.winners.slice(0, 5), losers: G.losers.slice(0, 5), new_queries: G.new_queries.slice(0, 5), lost_queries: G.lost_queries.slice(0, 5),
      striking_distance: G.striking.slice(0, 8).map(q => ({ query: q.query, position: r1(q.position), impressions: q.impressions, clicks: q.clicks, page: q.page })), ctr_gaps: G.ctr_gaps.slice(0, 5).map(q => ({ query: q.query, position: r1(q.position), impressions: q.impressions, ctr: r1(q.ctr * 1000) / 10, expected_ctr: Math.round(q.expected_ctr * 100), page: q.page })),
      top_pages: G.top_pages.slice(0, 8), decaying_pages: G.decaying_pages.slice(0, 5), rising_pages: G.rising_pages.slice(0, 5) } : { connected: false, error: G.error },
    analytics: A.connected ? { organic: A.organic, all_channels: A.total, organic_share_pct: A.organic_share, channels: A.channels.slice(0, 6), organic_landing_pages: A.landing.slice(0, 8) } : { connected: false, error: A.error },
    tracked_keywords: m.tracked.map(t => ({ keyword: t.keyword, source: t.source + (t.rung ? ' rung ' + t.rung : ''), search_console_position: G.connected ? (t.gsc_position ? r1(t.gsc_position) : 'no impressions in the period') : 'Search Console not connected', previous_position: G.connected && t.gsc_prev_position ? r1(t.gsc_prev_position) : null, impressions: G.connected ? t.impressions : null, clicks: G.connected ? t.clicks : null,
      live_google_position: t.serp_position == null ? 'not checked' : t.serp_position > 0 ? t.serp_position : t.serp_position === 0 ? 'not in the top 50' : 'check failed', live_check_date: t.serp_checked_at ? String(t.serp_checked_at).slice(0, 10) : null, page: t.page || t.serp_url || null })),
    ladder_pages: m.ladder_pages.map(p => ({ url: p.url, keyword: p.keyword, rung: p.rung, status: p.status, live: !!(p.page_exists || p.status === 'published'), indexed: (p.page_exists || p.status === 'published') ? p.indexed : 'not live yet', coverage: p.coverage || p.inspect_error || '' })),
    trends: m.trends.map(t => ({ keyword: t.keyword, direction: t.direction, change_pct: t.change_pct, peak: t.peak_date, rising_searches: (t.rising || []).slice(0, 5).map(r => r.query) })),
    pages_waiting_for_publish_link: (m.pending_publish || []).map(p => p.keyword + ' (' + p.days + ' days)'),
    ...((m.detected_published || []).length ? { pages_found_live_this_week: m.detected_published.map(f => f.keyword + ' -> ' + f.url + ' (tracking started)') } : {}),   // v4.8 publish detection
    search_console_notices: ((m.console || {}).notices || []).map(x => x.severity + ': ' + x.kind + ' — ' + x.subject + ' (' + String(x.received_at).slice(0, 10) + ')'),
    monthly_checkin: (m.console || {}).last_checkin ? { month: m.console.last_checkin.month, manual_action: m.console.last_checkin.manual_action, security_issue: m.console.last_checkin.security_issue, pages_not_indexed_sitewide: m.console.last_checkin.not_indexed_total >= 0 ? m.console.last_checkin.not_indexed_total : null, top_reasons: ((m.console.last_checkin.coverage || {}).reasons || []).slice(0, 3) } : (m.console && m.console.checkin_due ? 'due (not submitted this month)' : null),
    growth_monitors: (() => { const L = (nm) => { try { return $(nm).all().map(x => x.json).filter(r => r && r.site_id === m.site_id && !r.error).sort((x, y) => String(y.checked_at || y.audited_at).localeCompare(String(x.checked_at || x.audited_at)))[0] || null; } catch (e) { return null; } }; const av = L('Load AI Visibility (Site)'), bl = L('Load Backlink Snapshots (Site)'), au = L('Load Audits (Site)');
      return { ai_answers: av ? { mention_rate_pct: Number(av.mention_rate), citation_rate_pct: Number(av.citation_rate), share_of_voice_pct: Number(av.share_of_voice), alerts: av.alerts || '' } : 'not measured yet', backlinks: bl ? { referring_domains: Number(bl.referring_domains), new: Number(bl.new_links), lost: Number(bl.lost_links), important_lost: Number(bl.important_lost), spam_score: Number(bl.spam_score) } : 'not measured yet', technical: au ? { health: Number(au.health_score), critical: Number(au.critical), high: Number(au.high), audited: String(au.audited_at).slice(0, 10) } : 'not audited yet' }; })(),
    alerts: m.alerts.map(a => a.level + ': ' + a.text), computed_actions: m.actions.map(a => ({ priority: a.priority, action: a.action, why: a.why })) };
  return { json: { site_id: m.site_id, domain: m.domain, facts: JSON.stringify(facts) } }; });
