// Deterministic quality gate for the generated page. v5 adds: banned-phrase (AI cliché) detection, readability (Flesch),
// term coverage against the competitor term model / brief, specificity, section-length checks, the editor's critique,
// and a 0-100 CONTENT SCORE. Schema is generated here (page-type aware), never by the model.
const prev = $('Parse Brief').first().json;
const inItem = $input.first().json;
const rawOut = inItem.output;
let md = (typeof rawOut === 'string' ? rawOut : JSON.stringify(rawOut || '')).trim();
const round = ($runIndex || 0) + 1;
const critique = round === 1 ? (inItem.critique || null) : null;
let lastCritique = null; try { lastCritique = $('Parse Critique').first().json.critique || null; } catch (e) {}
const fixes = [];
const warnings = [];
const brief = prev.content_brief || {};
const kw = String(prev.keyword || '').toLowerCase();
const domain = prev.domain || '';
const today = new Date().toISOString().slice(0, 10);

const plain = (s) => String(s || '').replace(/\[([^\[\]]+)\]\([^)]*\)/g, '$1').replace(/[*_`>]+/g, '').replace(/\s+/g, ' ').trim();
const countWords = (t) => String(t || '').split(/\s+/).filter(Boolean).length;
const escRe = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// 1. Strip any schema/script the model added
const before0 = md;
md = md.replace(/<script[\s\S]*?<\/script>/gi, '').replace(/```(?:json|html)?\s*\{[\s\S]*?"@context"[\s\S]*?```/gi, '').trim();
if (md !== before0) fixes.push('Removed model-written schema/script blocks (schema is generated by the QA step)');

// 2. The word "placeholder" must never appear
const before1 = md;
md = md.replace(/\s*\((placeholders?|placeholder for [^)]*)\)/gi, '').replace(/\b(indicative\s+)?price placeholders?\b/gi, 'prices').replace(/\bplaceholders?\b/gi, 'details');
if (md !== before1) fixes.push('Removed the word "placeholder" from text');

// 3. Prices become [Price] unless the user gave prices (business facts / description)
const userText = String(prev.business || '') + ' ' + String(prev.business_facts || '') + ' ' + String(prev.case_facts_text || '');   // case-study facts (v4.4) are the client's own numbers
const userGavePrices = /\d/.test(userText) && /(\$|£|€|₹|\b(aed|sar|pkr|inr|usd|gbp|eur|zar|brl|mxn|rs)\b)/i.test(userText);
if (!userGavePrices) {
  const sym = { GBP: '£', USD: '\\$', CAD: '\\$', AUD: '\\$', NZD: '\\$', SGD: '\\$', PKR: '(?:Rs\\.?|PKR)', INR: '(?:Rs\\.?|₹|INR)', AED: '(?:AED|Dh)', SAR: '(?:SAR|SR)', EUR: '€', ZAR: 'R', BRL: 'R\\$', MXN: '\\$' }[prev.currency] || '[£$€]';
  const priceRe = new RegExp(sym + '\\s?\\d[\\d.,]*(\\s?(–|-|to)\\s?' + sym + '?\\s?\\d[\\d.,]*)?', 'g');
  const count = (md.match(priceRe) || []).length;
  if (count) { md = md.replace(priceRe, '[Price]'); fixes.push(`Replaced ${count} invented price(s) with [Price]`); }
}

// 4. Meta lines — and nothing else may sit between them and the H1 (models sometimes add "production notes")
const metaOf = (label) => { const m = md.match(new RegExp('^' + label + ':\\s*(.+)$', 'im')); return m ? m[1].trim() : ''; };
const metaTitle = metaOf('Title'), metaDesc = metaOf('Meta Description'), slug = metaOf('Slug');
{
  const h1At = md.search(/^# .+$/m);
  if (h1At > 0) {
    const head = md.slice(0, h1At);
    const metaLines = head.split('\n').filter(l => /^(Title|Meta Description|Slug|Primary Keyword|Secondary Keywords):/i.test(l.trim()));
    const other = head.split('\n').filter(l => l.trim() && !/^(Title|Meta Description|Slug|Primary Keyword|Secondary Keywords):/i.test(l.trim()));
    if (other.length) { md = metaLines.join('\n') + '\n\n' + md.slice(h1At); fixes.push('Removed ' + other.length + ' line(s) of notes that sat between the meta lines and the H1'); }
  }
}

// 5. Internal links: only real pages on the user's site; external links kept (they are citations)
const allowed = new Set();
const normUrl = (u) => String(u || '').trim().replace(/\/$/, '').toLowerCase();
(prev.internal_link_candidates || []).forEach(c => allowed.add(normUrl(c.url)));
(prev.site_urls || []).forEach(u => allowed.add(normUrl(u)));
if (prev.existing_page && prev.existing_page.url) allowed.add(normUrl(prev.existing_page.url));
if (domain) allowed.add(normUrl('https://' + domain));
const removedLinks = []; const externalUrls = [];
let internalLinks = 0, externalLinks = 0;
md = md.replace(/\[([^\[\]]+)\]\(([^)\s]+)\)/g, (m, text, url) => {
  let u = url.trim(); const isRelative = u.startsWith('/');
  if (isRelative) u = domain ? 'https://' + domain + u : u;
  const host = u.replace(/^https?:\/\//i, '').replace(/^www\./i, '').split(/[\/?#]/)[0].toLowerCase();
  const internal = !!domain && (host === domain || host.endsWith('.' + domain));
  if (internal || isRelative) { if (allowed.size && allowed.has(normUrl(u))) { internalLinks++; return '[' + text + '](' + u + ')'; } removedLinks.push(u); return text; }
  externalLinks++; externalUrls.push({ anchor: text, url: u, host }); return m;
});
if (removedLinks.length) fixes.push(`Removed ${removedLinks.length} link(s) to pages that do not exist on ${domain || 'the site'}: ` + removedLinks.slice(0, 4).join(', '));
// citations must point at sources the brief allowed (evidence plan) or at least be real-looking hosts
const allowedSources = new Set(((brief.evidence_plan || []).map(e => String(e.source_url || '').toLowerCase())).concat((prev.facts || []).map(f => String(f.url || '').toLowerCase())));
const TRUSTED = /(^|\.)(gov|edu|int|mil)(\.|$)|\.gov\.[a-z]{2}$|(^|\.)(microsoft|odoo|sap|oracle|netsuite|google|zoho|sage|xero|quickbooks|intuit|salesforce|hubspot|shopify|stripe|who|oecd|worldbank|imf|un|europa)\.(com|org|eu|int)$/i;
const unknownSources = externalUrls.filter(e => !TRUSTED.test(e.host) && allowedSources.size && ![...allowedSources].some(s => s && (e.url.toLowerCase().startsWith(s) || s.startsWith(e.url.toLowerCase()))));
if (unknownSources.length > 2) warnings.push('External links to sources not in the evidence plan: ' + unknownSources.slice(0, 3).map(e => e.host).join(', ') + ' — verify each one');
const trusted_sources = externalUrls.filter(e => TRUSTED.test(e.host)).map(e => e.host);

// 6. FAQs
const faqs = []; let cur = null, inAnswer = false;
for (const raw of md.split('\n')) {
  const l = raw.trim(); let m;
  if ((m = l.match(/^\**Q\d+[:.]\**\s*(.+)$/))) { cur = { q: m[1].replace(/\*+$/, '').trim(), a: '' }; faqs.push(cur); inAnswer = false; continue; }
  if ((m = l.match(/^\**A\d+[:.]\**\s*(.*)$/)) && cur) { cur.a = m[1]; inAnswer = true; continue; }
  if (inAnswer && l && !l.startsWith('#')) { cur.a += ' ' + l; continue; }
  if (!l || l.startsWith('#')) inAnswer = false;
}
const validFaqs = faqs.filter(f => f.q && f.a && countWords(f.a) >= 15);

// 7. Sections
const withoutMeta = md.replace(/^(Title|Meta Description|Slug|Primary Keyword|Secondary Keywords):.*$/gm, '');
const faqStart = withoutMeta.search(/^## (Frequently Asked Questions|FAQs?)/im);
const afterFaq = faqStart >= 0 ? withoutMeta.slice(faqStart + 5).search(/^## /m) : -1;
const faqPart = faqStart >= 0 ? withoutMeta.slice(faqStart, afterFaq >= 0 ? faqStart + 5 + afterFaq : undefined) : '';
const mainPart = withoutMeta.replace(faqPart, '');
const totalWords = countWords(withoutMeta), mainWords = countWords(mainPart), faqWords = countWords(faqPart);
const h1 = (md.match(/^# .+$/m) || [''])[0];
const h2s = md.match(/^## .+$/gm) || [];
const faqHeadings = h2s.filter(h => /faq|frequently asked/i.test(h)).length;
const lastH2 = h2s[h2s.length - 1] || '';
const qaMatch = withoutMeta.match(/^\**\s*Quick answer:?\**\s*(.+)$/im);
const answerWords = qaMatch ? countWords(plain(qaMatch[1])) : 0;
// per-section word counts vs the outline
const sections = []; { const parts = mainPart.split(/^## /m).slice(1); for (const p of parts) { const nl = p.indexOf('\n'); sections.push({ h2: plain(p.slice(0, nl)), words: countWords(p.slice(nl + 1)) }); } }
const outline = brief.outline || [];
const thinSections = sections.filter(s => { const o = outline.find(x => x.h2 && plain(x.h2).toLowerCase() === s.h2.toLowerCase()); const target = o ? Number(o.target_words) || 0 : 0; return target >= 150 && s.words < target * 0.6; }).map(s => s.h2 + ' (' + s.words + ' words)');

// 8. Keyword checks — natural variants count ("erp systems in the uae", "ERP system in UAE", hyphens)
const flexRe = (phrase, flags) => new RegExp('\\b' + phrase.toLowerCase().split(/[\s-]+/).filter(Boolean).map(w => escRe(w.replace(/(?:ies|es|s)$/, '')) + '(?:ies|es|s)?').join('[\\s-]+(?:(?:the|a|an|of|for|in|to|and)\\s+)?') + '\\b', flags);
const kwRe = kw ? flexRe(kw, 'gi') : null;
const kwCount = kwRe ? (withoutMeta.match(kwRe) || []).length : 0;
const density = totalWords ? +(kwCount / totalWords * 100).toFixed(2) : 0;
const first100 = plain(mainPart.replace(/^#.*$/gm, '')).split(/\s+/).slice(0, 100).join(' ').toLowerCase();

// 9. Unverified statistics: numbers outside brackets, tables and cited sentences
const bodyPlain = plain(withoutMeta.replace(/\|[^\n]*\|/g, ''));
const citedSentences = new Set();
withoutMeta.split(/(?<=[.!?])\s+/).forEach(s => { if (/\]\(https?:\/\//.test(s)) citedSentences.add(plain(s)); });
const noBrackets = withoutMeta.replace(/\[[^\]]*\]\([^)]*\)/g, ' CITED ').replace(/\[[^\]]*\]/g, '').replace(/\|[^\n]*\|/g, '');
const statHits = new Set();
for (const s of noBrackets.split(/(?<=[.!?])\s+/)) {
  if (/CITED/.test(s)) continue;
  for (const m of s.matchAll(/\b\d[\d,.]*\s?%/g)) statHits.add(m[0].trim());
  for (const m of s.matchAll(/\b(over|more than|up to|nearly|around|approximately|about)\s+\d[\d,.]*\+?(\s?%|\s+\w+)?/gi)) statHits.add(m[0].trim());
  for (const m of s.matchAll(/\b\d[\d,.]*\+\s+(years?|clients?|customers?|projects?|users?|students?|universities|schools|companies|installations?|reviews?|countries|awards?)\b/gi)) statHits.add(m[0].trim());
}
const clientNums = (String(prev.business_facts || '') + ' ' + String(prev.case_facts_text || '')).toLowerCase();   // numbers the client gave (facts, case studies) need no external source
const stats = [...statHits].filter(s => !/^(19|20)\d\d/.test(s)).filter(s => !clientNums.includes(s.toLowerCase().replace(/^(over|more than|up to|nearly|around|approximately|about)\s+/, ''))).slice(0, 8);

// 10. Banned phrases (AI clichés and filler)
const BANNED = ["in today's fast-paced world", 'in the ever-evolving', 'ever-evolving landscape', 'delve', 'dive into', 'unlock', 'unleash', 'seamless', 'seamlessly', 'robust', 'leverage', 'cutting-edge', 'game-changer', 'game-changing', 'revolutioni', 'elevate your', 'empower', 'navigate the complexities', 'look no further', "it's important to note", 'it is important to note', 'at the end of the day', 'in conclusion', 'comprehensive solution', 'tailored solutions', 'harness the power', "whether you're a", 'a testament to', 'crucial', 'paramount', 'realm', 'tapestry', 'embark', 'foster', 'streamline', 'synergy', 'holistic', 'best-in-class', 'world-class', 'state-of-the-art', 'top-notch', 'one-stop shop', 'in this article', 'in this guide, we', 'without further ado', 'unparalleled', 'transformative', 'in the digital age', 'stay ahead of the curve', 'the bottom line is', 'when it comes to', 'a wide range of'];
const lower = bodyPlain.toLowerCase();
const banned_found = BANNED.map(p => ({ phrase: p, count: (lower.match(new RegExp(escRe(p), 'g')) || []).length })).filter(x => x.count > 0).sort((a, b) => b.count - a.count);
const bannedCount = banned_found.reduce((s, x) => s + x.count, 0);

// 11. Readability (Flesch reading ease, approximate syllables), sentence length, passive voice
const sentences = bodyPlain.split(/(?<=[.!?])\s+/).map(s => s.trim()).filter(s => countWords(s) >= 3);
const sentWords = sentences.map(countWords);
const avgSentence = sentWords.length ? +(sentWords.reduce((a, b) => a + b, 0) / sentWords.length).toFixed(1) : 0;
const longSentences = sentWords.filter(n => n > 28).length;
const syl = (w) => { w = w.toLowerCase().replace(/[^a-z]/g, ''); if (!w) return 0; if (w.length <= 3) return 1; const m = w.replace(/(?:[^laeiouy]es|ed|[^laeiouy]e)$/, '').replace(/^y/, '').match(/[aeiouy]{1,2}/g); return m ? m.length : 1; };
const wordsArr = bodyPlain.split(/\s+/).filter(Boolean);
const syllables = wordsArr.reduce((s, w) => s + syl(w), 0);
const flesch = wordsArr.length && sentences.length ? +(206.835 - 1.015 * (wordsArr.length / sentences.length) - 84.6 * (syllables / wordsArr.length)).toFixed(1) : null;
const passive = sentences.filter(s => /\b(is|are|was|were|been|being|be)\s+(\w+ed|built|made|done|seen|known|given|taken|chosen|written)\b/i.test(s)).length;
const passive_pct = sentences.length ? Math.round(passive / sentences.length * 100) : 0;

// 12. Term coverage (brief terms first, else the competitor term model)
const termList = (brief.terms_to_use || []).map(t => ({ term: String(t.term || t).toLowerCase(), min: Number(t.min_count) || 1 }))
  .concat((prev.term_model || []).slice(0, 25).map(t => ({ term: t.term, min: 1 })))
  .filter((t, i, a) => t.term && a.findIndex(x => x.term === t.term) === i).slice(0, 30);
const termCoverage = termList.map(t => ({ term: t.term, target: t.min, found: (bodyPlain.match(flexRe(t.term, 'gi')) || []).length })).map(t => ({ ...t, ok: t.found >= t.target }));
const coverage = termCoverage.length ? termCoverage.filter(t => t.ok).length / termCoverage.length : 1;
const missingTerms = termCoverage.filter(t => !t.ok).slice(0, 10).map(t => t.term);

// 13. Specificity: numbers, examples, steps, decision rules per 100 words
const specHits = (bodyPlain.match(/\b\d[\d,.%]*\b/g) || []).length + (lower.match(/\b(for example|for instance|such as|e\.g\.|step \d|case study|in practice|choose .* if|rule of thumb)\b/g) || []).length;
const specificity = wordsArr.length ? +(specHits / wordsArr.length * 100).toFixed(2) : 0;
// snippet targets answered?
const snippetTargets = brief.snippet_targets || [];
const unansweredSnippets = snippetTargets.filter(t => t.question && !new RegExp('^#{2,3}\\s*' + escRe(plain(t.question).replace(/\?$/, '')), 'im').test(md)).map(t => t.question).slice(0, 4);

// 14. Warnings
const target = brief.target_word_count || 800;
if (mainWords < target * 0.8) warnings.push(`Main content is short: ${mainWords} words vs target ${target}`);
if (mainWords > target * 1.25) warnings.push(`Main content is too long: ${mainWords} words vs target ${target} — cut repetition and secondary detail, do not add anything`);
if (thinSections.length) warnings.push('Sections far below their target length: ' + thinSections.slice(0, 4).join('; '));
if (!metaTitle) warnings.push('Meta title line missing');
else { if (metaTitle.length > 60) warnings.push(`Meta title is ${metaTitle.length} characters (max 60)`); if (metaTitle.length < 30) warnings.push(`Meta title is only ${metaTitle.length} characters (aim for 50-60)`); if (kw && !flexRe(kw, 'i').test(metaTitle)) warnings.push('Primary keyword missing from the meta title'); }
if (!metaDesc) warnings.push('Meta description line missing');
else { if (metaDesc.length > 155) warnings.push(`Meta description is ${metaDesc.length} characters (max 155)`); if (metaDesc.length < 70) warnings.push(`Meta description is only ${metaDesc.length} characters (aim for 120-155)`); }
if (slug && !/^\/?[a-z0-9]+(-[a-z0-9]+)*\/?$/.test(slug)) warnings.push('Slug should be lowercase words joined by hyphens');
if (!h1) warnings.push('H1 missing'); else if (kw && !flexRe(kw, 'i').test(h1)) warnings.push('Primary keyword missing from H1');
if (kw && !flexRe(kw, 'i').test(first100)) warnings.push('Primary keyword not in the first 100 words');
if (kwCount < 3) warnings.push(`Primary keyword used only ${kwCount} time(s)`);
if (density > 2) warnings.push(`Keyword density is high (${density}%) — risk of keyword stuffing`);
if (h2s.length < 4) warnings.push(`Only ${h2s.length} H2 sections (brief expects ${outline.length || 'more'})`);
if (!qaMatch) warnings.push('Quick answer block missing (a 40-70 word direct answer right after the introduction)');
else if (answerWords < 35 || answerWords > 90) warnings.push(`Quick answer is ${answerWords} words (aim for 40-70)`);
if (validFaqs.length < 5) warnings.push(`Only ${validFaqs.length} complete FAQs found (need 5+, answers 40-70 words)`);
if (faqHeadings > 1) warnings.push('Duplicate FAQ sections found');
if (/faq|frequently asked/i.test(lastH2)) warnings.push('CTA section should come after the FAQs');
if (!/\|.*\|/.test(md)) warnings.push('Comparison table missing');
if (/guarantee/i.test(md) && !prev.business) warnings.push('Contains a guarantee claim — please verify');
if (stats.length) warnings.push('Unverified statistics that need a linked source or a [Statistic] marker: ' + stats.join('; '));
if ((prev.internal_link_candidates || []).length > 1 && internalLinks === 0) warnings.push('No internal links to existing pages on the site');
if (bannedCount) warnings.push('Filler / AI-cliché phrases to rewrite (' + bannedCount + '): ' + banned_found.slice(0, 8).map(b => '"' + b.phrase + '"' + (b.count > 1 ? ' x' + b.count : '')).join(', '));
if (flesch != null && flesch < 30) warnings.push(`Hard to read (Flesch ${flesch}, average sentence ${avgSentence} words) — shorten sentences and use plainer words`);
if (longSentences > Math.max(3, sentences.length * 0.12)) warnings.push(`${longSentences} sentences longer than 28 words — split them`);
if (passive_pct > 25) warnings.push(`Passive voice in about ${passive_pct}% of sentences — rewrite in active voice`);
if (termCoverage.length >= 8 && coverage < 0.6) warnings.push('Topic coverage is thin — competitors cover these terms and this page does not: ' + missingTerms.join(', '));
if (wordsArr.length > 400 && specificity < 0.6) warnings.push(`Too generic (${specificity} specifics per 100 words) — add concrete examples, numbers with sources, steps or decision rules`);
if (unansweredSnippets.length) warnings.push('Snippet questions from the brief that have no matching heading: ' + unansweredSnippets.join(' | '));
if (critique && Array.isArray(critique.problems)) critique.problems.filter(p => /high|medium/i.test(p.severity || '')).slice(0, 8).forEach(p => warnings.push('Editor review: ' + [p.location ? '"' + String(p.location).slice(0, 80) + '"' : '', p.issue, p.fix ? 'Fix: ' + p.fix : ''].filter(Boolean).join(' — ')));

// 15. Content score (0-100)
const structuralChecks = [!!metaTitle && metaTitle.length <= 60, !!metaDesc && metaDesc.length <= 155, !!h1, h2s.length >= 4, !!qaMatch, validFaqs.length >= 5, /\|.*\|/.test(md), !/faq|frequently asked/i.test(lastH2), internalLinks > 0 || (prev.internal_link_candidates || []).length <= 1, kwCount >= 3 && density <= 2];
const structure_pts = 25 * structuralChecks.filter(Boolean).length / structuralChecks.length;
const coverage_pts = 25 * coverage;
const readability_pts = flesch == null ? 10 : (flesch >= 40 && avgSentence <= 22 ? 15 : (flesch >= 30 && avgSentence <= 26 ? 10 : 4));   // B2B copy normally scores 30-55
const specificity_pts = 10 * Math.min(1, specificity / 0.8);
const banned_pts = Math.max(0, 10 - 2 * bannedCount);
const length_pts = 15 * (1 - Math.min(1, Math.abs(mainWords - target) / target));
const content_score = Math.round(structure_pts + coverage_pts + readability_pts + specificity_pts + banned_pts + length_pts);

// 16. Schema (deterministic, page-type aware). v4.4: the author as a Person (from the business profile), the expert reviewer, LocalBusiness
//     for local pages, VideoObject for pages with a video, an ItemList of the cluster pages for hub pages. Unknown values stay [placeholders].
const P = prev.site_profile || {}; const PA = P.address || {}; const AU = prev.author || null; const RV = prev.reviewer || null; const role = prev.page_role || 'standard';
const bizName = String(P.business_name || ((prev.site_description && prev.site_description.business_name) ? prev.site_description.business_name : '')).trim();
const biz = bizName || '[Your Business Name]';
const pageUrl = (prev.existing_page && prev.existing_page.url) || (domain ? 'https://' + domain + '/' + String(slug || '').replace(/^\/|\/$/g, '') : '[Page URL]');
const h1Text = plain(h1.replace(/^#\s*/, '')) || metaTitle;
const home = domain ? 'https://' + domain + '/' : '[Website URL]';
const slugId = (t) => String(t || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const org = { '@type': 'Organization', ...(domain ? { '@id': home + '#organization' } : {}), name: biz, url: home, ...(P.logo_url ? { logo: P.logo_url } : {}) };
const blocks = [];
const pt = String(prev.page_type || '').toLowerCase();
const articleLike = /blog|guide|article|pillar|hub|case stud/.test(pt);
const authorRef = AU ? { '@type': 'Person', ...(domain ? { '@id': home + '#author-' + slugId(AU.name) } : {}), name: AU.name, ...(AU.url ? { url: AU.url } : {}) } : { '@type': 'Person', name: '[Author Name]', url: '[Author Page URL]' };
if (articleLike) {
  blocks.push({ type: 'Article', json: { '@context': 'https://schema.org', '@type': 'Article', headline: h1Text, description: plain(metaDesc), author: authorRef, publisher: org, datePublished: today, dateModified: today, mainEntityOfPage: { '@type': 'WebPage', '@id': pageUrl }, keywords: [prev.keyword, ...(brief.secondary_keywords || []).slice(0, 5)].filter(Boolean).join(', '), ...(role === 'case_study' ? { articleSection: 'Case study' } : {}) } });
  const person = AU ? { '@context': 'https://schema.org', ...authorRef, ...(AU.job_title ? { jobTitle: AU.job_title } : {}), ...((AU.bio || AU.credentials) ? { description: [AU.bio, AU.credentials && !String(AU.bio || '').includes(AU.credentials) ? AU.credentials : ''].filter(Boolean).join(' ').slice(0, 600) } : {}),
      ...(AU.image_url ? { image: AU.image_url } : {}), ...((AU.same_as || []).length ? { sameAs: AU.same_as } : {}), ...((AU.knows_about || []).length ? { knowsAbout: AU.knows_about } : {}), worksFor: domain ? { '@id': home + '#organization', name: biz } : { '@type': 'Organization', name: biz } }
    : { '@context': 'https://schema.org', '@type': 'Person', name: '[Author Name]', jobTitle: '[Job title]', description: '[Two-sentence bio with credentials]', url: '[Author Page URL]', sameAs: ['[LinkedIn profile URL]'], worksFor: { '@type': 'Organization', name: biz } };
  blocks.push({ type: 'Person', note: AU ? 'The author (business profile). Link the byline to the author page.' : 'No business profile on file: fill in the author, or set up the profile once (form "Set up my business profile" / API mode profile) so every page carries it.', json: person });
  if (RV) blocks.push({ type: 'WebPage', note: 'Expert review (reviewedBy / lastReviewed).', json: { '@context': 'https://schema.org', '@type': 'WebPage', '@id': pageUrl, url: pageUrl, name: h1Text, reviewedBy: { '@type': 'Person', name: RV.name, ...(RV.job_title ? { jobTitle: RV.job_title } : {}), ...(RV.url ? { url: RV.url } : {}) }, lastReviewed: today } });
} else if (pt.includes('product')) {
  blocks.push({ type: 'Product', json: { '@context': 'https://schema.org', '@type': 'Product', name: h1Text, description: plain(metaDesc), brand: { '@type': 'Brand', name: biz }, url: pageUrl, offers: { '@type': 'Offer', priceCurrency: prev.currency || 'USD', price: '[Price as a number]', availability: 'https://schema.org/InStock', url: pageUrl } } });
} else if (role === 'local') {
  const area = String(prev.local_area || '').trim() || '[City]';
  const LBT = [[/account|tax|bookkeep|audit/i, 'AccountingService'], [/legal|law|notar/i, 'LegalService'], [/financ|insur|bank/i, 'FinancialService'], [/medic|clinic|dental|health|doctor/i, 'MedicalBusiness'], [/restaurant|caf|food/i, 'FoodEstablishment'], [/store|shop|retail/i, 'Store'], [/home|plumb|electric|clean|repair|construct/i, 'HomeAndConstructionBusiness'], [/real estate|property/i, 'RealEstateAgent'], [/.+/, 'ProfessionalService']];
  const lbType = P.business_type ? (LBT.find(x => x[0].test(P.business_type)) || [, 'LocalBusiness'])[1] : 'LocalBusiness';
  const hoursOk = /^((Mo|Tu|We|Th|Fr|Sa|Su)(-(Mo|Tu|We|Th|Fr|Sa|Su))?(,(Mo|Tu|We|Th|Fr|Sa|Su))*\s+\d{2}:\d{2}-\d{2}:\d{2}[;,]?\s*)+$/.test(String(P.opening_hours || '').trim());
  const lbId = domain ? home + '#business' : undefined;
  blocks.push({ type: lbType, note: 'Local business details from the business profile' + (P.phone && PA.street ? '.' : ': fill in every [bracketed] value; name, address and phone must match the Google Business Profile exactly.'), json: { '@context': 'https://schema.org', '@type': lbType, ...(lbId ? { '@id': lbId } : {}), name: biz, url: home,
    telephone: P.phone || '[Phone]', ...(P.public_email ? { email: P.public_email } : {}), address: { '@type': 'PostalAddress', streetAddress: PA.street || '[Street address]', addressLocality: PA.city || area, ...(PA.region ? { addressRegion: PA.region } : {}), ...(PA.postal_code ? { postalCode: PA.postal_code } : {}), addressCountry: PA.country_code || prev.country_iso || '[Country code]' },
    areaServed: [area, ...(P.service_areas || []).filter(a => a.toLowerCase() !== area.toLowerCase())].slice(0, 12).map(a => ({ '@type': 'Place', name: a })), ...(hoursOk ? { openingHours: String(P.opening_hours).trim().split(/[;,]\s*(?=(?:Mo|Tu|We|Th|Fr|Sa|Su))/) } : {}),
    ...(P.price_range ? { priceRange: P.price_range } : {}), ...(P.logo_url ? { logo: P.logo_url, image: P.logo_url } : {}), ...(P.map_url ? { hasMap: P.map_url } : {}) } });
  blocks.push({ type: 'Service', json: { '@context': 'https://schema.org', '@type': 'Service', name: h1Text, serviceType: prev.keyword, description: plain(metaDesc), provider: lbId ? { '@id': lbId, name: biz } : org, areaServed: { '@type': 'Place', name: area }, url: pageUrl } });
} else {
  blocks.push({ type: 'Service', json: { '@context': 'https://schema.org', '@type': 'Service', name: h1Text, serviceType: prev.keyword, description: plain(metaDesc), provider: org, areaServed: prev.country || '[Country]', url: pageUrl } });
}
const V = prev.video || null;
if (V && V.url) {
  const ytWatch = V.provider === 'youtube' && V.id ? 'https://www.youtube.com/watch?v=' + V.id : V.url;
  const clips = (V.chapters || []).map((c, i, a) => ({ '@type': 'Clip', name: c.name, startOffset: c.start_seconds, ...(a[i + 1] ? { endOffset: a[i + 1].start_seconds } : (V.duration_seconds ? { endOffset: V.duration_seconds } : {})), url: V.provider === 'youtube' ? ytWatch + '&t=' + c.start_seconds + 's' : V.url + '#t=' + c.start_seconds }));
  blocks.push({ type: 'VideoObject', note: (V.missing || []).filter(m => m !== 'transcript').length ? 'Fill in: ' + V.missing.filter(m => m !== 'transcript').join(', ') + ' (YouTube Studio shows them).' : 'Video details read from the video page.', json: { '@context': 'https://schema.org', '@type': 'VideoObject', name: V.title || h1Text, description: String(V.description || plain(metaDesc)).slice(0, 2000),
    thumbnailUrl: V.thumbnail_url ? [V.thumbnail_url] : ['[Thumbnail URL]'], uploadDate: V.upload_date || '[Upload date, YYYY-MM-DD]', ...(V.duration_iso ? { duration: V.duration_iso } : {}), ...(V.embed_url ? { embedUrl: V.embed_url } : {}), ...(V.provider === 'file' ? { contentUrl: V.url } : {}), ...(clips.length ? { hasPart: clips } : {}) } });
}
const HP = (prev.hub_pages || []).filter(p => p && p.url);
if (role === 'hub' && HP.length) blocks.push({ type: 'ItemList', note: 'The cluster pages this hub links to' + (HP.some(p => p.planned) ? '; remove planned pages that are not live yet, or publish them first.' : '.'), json: { '@context': 'https://schema.org', '@type': 'ItemList', name: h1Text + ': guides in this series', itemListElement: HP.map((p, i) => ({ '@type': 'ListItem', position: i + 1, name: p.keyword ? p.keyword.charAt(0).toUpperCase() + p.keyword.slice(1) : p.url, url: p.url })) } });
blocks.push({ type: 'BreadcrumbList', json: { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: home }, { '@type': 'ListItem', position: 2, name: h1Text, item: pageUrl }] } });
if (validFaqs.length) blocks.push({ type: 'FAQPage', note: 'Google stopped showing FAQ rich results in May 2026; keep for other engines and AI assistants, or drop it.', json: { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: validFaqs.map(f => ({ '@type': 'Question', name: plain(f.q), acceptedAnswer: { '@type': 'Answer', text: plain(f.a) } })) } });
// E-E-A-T notes for the report (not QA warnings: they never trigger an editor round)
const eeat_notes = [];
if (articleLike && !AU) eeat_notes.push('No author on file: the byline, author box and Person schema carry [placeholders]. Set up the business profile once (author name, title, credentials, bio, profile links).');
if (AU && !AU.has_author_page) eeat_notes.push('The author has no profile page URL: an author page on the site (bio, credentials, articles) strengthens attribution.');
if (AU && !(AU.same_as || []).length) eeat_notes.push('Add the author\'s LinkedIn or other public profiles (sameAs) to the business profile.');
const insightPrompts = (md.match(/\[Author insight:[^\]]*\]/gi) || []).length;
if (insightPrompts) eeat_notes.push(insightPrompts + ' [Author insight: ...] line(s) for the author to complete with first-hand experience before publishing.');
if (role === 'local' && !(P.phone && PA.street)) eeat_notes.push('Local page without a full address and phone on file: fill in the business profile so the NAP block and LocalBusiness schema are complete.');
if (V && (V.missing || []).length) eeat_notes.push('Video: missing ' + V.missing.join(', ') + (V.missing.includes('transcript') ? ' (paste the transcript from YouTube Studio → Subtitles)' : '') + '.');
if (role === 'hub' && HP.some(p => p.planned)) eeat_notes.push(HP.filter(p => p.planned).length + ' cluster page(s) are planned and not live yet: publish them before the hub, or drop their links until they are.');
fixes.push('Generated ' + blocks.map(b => b.type).join(' + ') + ' schema');

const passed = warnings.length === 0 && content_score >= 80 && Math.abs(mainWords - target) <= target * 0.25;
// v4.6: the editor pass (a full rewrite) runs only when it can still improve the page. It is skipped when the draft already scores 90+, the editorial
// review rates it 85+ with no high-severity problem, the length is on target and the only open notes are style notes (passive voice, long
// sentences, medium review remarks). Every SEO check (meta, H1 / keyword, quick answer, FAQs, table, CTA, links, sources, statistics, coverage,
// specificity, fillers, readability, snippet questions) still forces the editor pass; open style notes stay in the report.
const STYLE_ONLY = /^(Passive voice in about|\d+ sentences longer than 28 words|Editor review: )/;
const crit = critique || lastCritique || {};
const highProblem = (crit.problems || []).some(p => /high|critical/i.test(p.severity || ''));
const editor_needed = !passed && !(content_score >= 90 && crit.score != null && Number(crit.score) >= 85 && !highProblem && Math.abs(mainWords - target) <= target * 0.25 && warnings.every(w => STYLE_ONLY.test(w)));
if (!passed && !editor_needed && round === 1) fixes.push('Editor pass skipped: the draft met every SEO check (score ' + content_score + ', review ' + crit.score + '); the style notes below are left for a final read');
return [{ json: { ...prev, output: md, qa_round: round, meta: { title: metaTitle, description: metaDesc, slug }, schema_blocks: blocks, critique: critique || lastCritique || null,
  content_qa: { round, passed, editor_needed, content_score, score_breakdown: { structure: Math.round(structure_pts), coverage: Math.round(coverage_pts), readability: Math.round(readability_pts), specificity: Math.round(specificity_pts), clean_language: Math.round(banned_pts), length: Math.round(length_pts) },
    total_words: totalWords, main_content_words: mainWords, faq_words: faqWords, target_word_count: target, sections,
    keyword_mentions: kwCount, keyword_density_pct: density, h2_count: h2s.length, faq_count: validFaqs.length, internal_links: internalLinks, external_links: externalLinks, sources_cited: externalUrls.slice(0, 15),
    answer_block_words: answerWords, meta_title_length: metaTitle.length, meta_description_length: metaDesc.length, unverified_statistics: stats,
    trusted_sources, banned_phrases: banned_found, readability: { flesch, avg_sentence_words: avgSentence, long_sentences: longSentences, passive_pct }, term_coverage: termCoverage, coverage_pct: Math.round(coverage * 100), missing_terms: missingTerms, specificity_per_100_words: specificity,
    critic_score: (critique || lastCritique || {}).score ?? null, critic_verdict: (critique || lastCritique || {}).verdict || null,
    schema_types: blocks.map(b => b.type), eeat_notes, page_role: role, auto_fixes: fixes, warnings } } }];
