// Turns the Search Console answers (sitemaps, search performance, URL inspections) and the sitemap-vs-crawl comparison into audit findings,
// a "search_console" block and a "site_structure" block for the report; then hands the audit item on to Build Site Issues.
const plan = $('GSC Audit Plan').first().json; const base = plan.base || {};
const grab = (name) => { try { return $(name).all().map(i => i.json); } catch (e) { return []; } };
const first = (name) => { try { return ($(name).first() || {}).json || null; } catch (e) { return null; } };
const gErr = (r) => { if (!r) return 'no response'; const e = r.error; if (!e) return null; if (typeof e === 'string') return e.slice(0, 200); const ctx = (e.context && e.context.data) || {}; const inner = (ctx.error && typeof ctx.error === 'object') ? ctx.error : null; return String((inner && inner.message) || (ctx.error_description ? String(ctx.error || 'error') + ': ' + ctx.error_description : '') || e.message || e.description || e.status || JSON.stringify(e)).slice(0, 200); };
const same = (a, b) => String(a || '').replace(/\/$/, '').toLowerCase() === String(b || '').replace(/\/$/, '').toLowerCase();
const path = (u) => String(u || '').replace(/^https?:\/\/[^\/]+/, '') || '/';
const findings = [], works = []; const CAT = 'Crawlability & Indexing';
const F = (severity, title, why, fix, evidence, urls, count, pct) => findings.push({ category: CAT, severity, title, why, fix, evidence: evidence || '', affected_count: count == null ? null : count, affected_pct: pct == null ? 100 : pct, sample_urls: (urls || []).slice(0, 5), scope: urls && urls.length ? 'pages' : 'site' });
// ---- sitemap file(s) read from the site ----
const bodyOf = (r) => { const b = r && (r.body != null ? r.body : r.data); return typeof b === 'string' ? b : (b ? JSON.stringify(b) : ''); };   // the HTTP node puts text responses under `data` (live finding 2026-10-02)
const key = (u) => String(u || '').trim().toLowerCase().replace(/^https?:\/\//, '').replace(/^www\./, '').replace(/[?#].*$/, '').replace(/\/$/, '');   // host-agnostic URL key: crawls report www while sitemaps/canonicals may not
const sm = first('Fetch Sitemap (Audit)') || {}; const smStatus = Number(sm.statusCode) || (sm.error ? 0 : 200); const smBody = bodyOf(sm);
const locsOf = (b) => (String(b || '').match(/<loc>\s*([^<\s]+)\s*<\/loc>/gi) || []).map(x => x.replace(/<\/?loc>/gi, '').trim());
let sitemapUrls = []; const isIndex = /<sitemapindex/i.test(smBody); let childCount = 0;
if (smStatus === 200 && !isIndex) sitemapUrls = locsOf(smBody);
if (smStatus === 200 && isIndex) { childCount = locsOf(smBody).length; for (const c of grab('Fetch Sitemap Children (Audit)')) if (c && !c.error) sitemapUrls.push(...locsOf(bodyOf(c))); }
sitemapUrls = [...new Set(sitemapUrls.map(key))].slice(0, 5000);
const sitemapKnown = smStatus === 200 && sitemapUrls.length > 0;
// ---- site structure from the crawl ----
const pages = plan.pages || []; const crawled = new Set(pages.map(p => key(p.url)));
const depthBuckets = { 0: 0, 1: 0, 2: 0, 3: 0, '4+': 0 }; for (const p of pages) { if (p.depth == null) continue; depthBuckets[p.depth >= 4 ? '4+' : p.depth] += 1; }
const withDepth = pages.filter(p => p.depth != null).length; const within3 = pages.filter(p => p.depth != null && p.depth <= 3).length;
const sections = {}; for (const p of pages) { const seg = path(p.url).split('/').filter(Boolean)[0] || '(home)'; sections[seg] = (sections[seg] || 0) + 1; }
const topSections = Object.entries(sections).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([name, count]) => ({ section: '/' + (name === '(home)' ? '' : name + '/'), pages: count }));
const indexablePages = pages.filter(p => p.indexable);
const notInSitemap = sitemapKnown ? indexablePages.filter(p => !sitemapUrls.includes(key(p.url))) : [];
const crawlComplete = plan.crawl_finished && plan.pages_crawled < plan.crawl_limit;
const sitemapOnly = (sitemapKnown && crawlComplete) ? sitemapUrls.filter(u => !crawled.has(u)).map(u => 'https://' + u) : [];
const sitemapBroken = sitemapKnown ? pages.filter(p => sitemapUrls.includes(key(p.url)) && (p.status !== 200)) : [];
if (withDepth) { if (within3 / withDepth >= 0.9) works.push('Shallow site structure: ' + Math.round(within3 / withDepth * 100) + '% of crawled pages are within 3 clicks of the homepage'); }
if (sitemapKnown && indexablePages.length && notInSitemap.length / indexablePages.length >= 0.2) F('Medium', 'Indexable pages missing from the XML sitemap', 'Google still finds them through links, but a complete sitemap is the fastest way to get new and updated pages crawled.', 'Regenerate the sitemap to include every indexable page (most CMS SEO plugins do this automatically) and resubmit it.', notInSitemap.length + ' of ' + indexablePages.length + ' crawled indexable pages are not listed in sitemap.xml', notInSitemap.map(p => p.url), notInSitemap.length, Math.round(notInSitemap.length / indexablePages.length * 100));
if (sitemapOnly.length) F('Medium', 'Sitemap URLs that no internal link reaches', 'These pages exist only in the sitemap: Google may crawl them, but without internal links they rarely rank and visitors cannot find them.', 'Link to them from relevant pages (navigation, hub pages, related articles) or remove them from the sitemap if they should not rank.', sitemapOnly.length + ' sitemap URLs were not reached by a complete crawl of ' + plan.pages_crawled + ' pages', sitemapOnly, sitemapOnly.length, sitemapUrls.length ? Math.round(sitemapOnly.length / sitemapUrls.length * 100) : 100);
if (sitemapBroken.length) F('Medium', 'Sitemap lists pages that do not return 200', 'Redirected or broken URLs in the sitemap waste crawl budget and make Google trust the sitemap less.', 'Remove redirected and broken URLs from the sitemap; list only final, 200-status URLs.', sitemapBroken.map(p => p.status).join(', ') + ' status codes found for sitemap URLs', sitemapBroken.map(p => p.url), sitemapBroken.length, Math.round(sitemapBroken.length / sitemapUrls.length * 100));
if (smStatus !== 200) F('Low', 'sitemap.xml could not be read at the standard location', 'Google looks for /sitemap.xml and the robots.txt reference; a missing or non-standard sitemap slows discovery.', 'Serve the sitemap at /sitemap.xml (or reference its real location in robots.txt).', 'HTTP ' + smStatus + ' for ' + plan.sitemap_url, [], null, 100);
else if (!sitemapUrls.length) F('Low', 'The XML sitemap contains no URLs', 'An empty sitemap gives Google nothing to crawl.', 'Regenerate the sitemap with the site\'s indexable pages.', plan.sitemap_url + (isIndex ? ' is an index of ' + childCount + ' sitemaps that could not be read' : ' is empty'), [], null, 100);
else works.push('XML sitemap lists ' + sitemapUrls.length + ' URLs' + (isIndex ? ' (index of ' + childCount + ' sitemaps' + (childCount > 3 ? ', first 3 read' : '') + ')' : ''));
// ---- Search Console ----
const reqs = grab('GSC Audit Requests'); const res = grab('GSC Audit Query'); const plan1 = reqs[0] || {};
const connected = !!plan1.connected; const scErr = plan1.connected ? null : (plan1.error || 'not connected');
let search_console = { connected, property: plan1.property || '', permission: plan1.permission || '', error: scErr, sitemaps: [], totals: null, top_pages: [], top_queries: [], inspections: [], coverage: {}, not_indexed: [], canonical_mismatch: [], not_in_sitemap_but_shown: [], rich_results: [] };
if (!connected) {
  F('Info', 'Search Console not connected: sitemap status, index coverage and search performance could not be checked', 'Only Search Console tells you which pages Google has indexed, which it rejected and why, and which queries bring impressions.', 'Add the service account e-mail (see the tracking set-up) as a Full user of the property in Search Console → Settings → Users and permissions, then re-run the audit.', scErr, [], null, 100);
  findings[findings.length - 1].scoring = false;   // a note about missing data, never a deduction
} else {
  const rowsOf = (r) => (r && Array.isArray(r.rows)) ? r.rows : [];
  const smr = first('GSC Sitemaps (Audit)') || {}; const smErr = gErr(smr);
  const sitemaps = Array.isArray(smr.sitemap) ? smr.sitemap.map(s => ({ path: s.path, submitted: s.lastSubmitted || '', downloaded: s.lastDownloaded || '', pending: !!s.isPending, index: !!s.isSitemapsIndex, warnings: Number(s.warnings) || 0, errors: Number(s.errors) || 0, urls: (s.contents || []).reduce((n, c) => n + (Number(c.submitted) || 0), 0) })) : [];
  search_console.sitemaps = sitemaps; search_console.sitemaps_error = smErr;
  if (!smErr && !sitemaps.length) F('High', 'No XML sitemap submitted to Search Console', 'Google discovers and re-crawls pages faster when the sitemap is submitted; without it, new pages depend on links alone and you get no sitemap error reports.', 'Submit ' + plan.sitemap_url + ' in Search Console → Sitemaps.', 'Search Console lists no sitemap for ' + plan1.property, [], null, 100);
  for (const s of sitemaps) {
    if (s.errors) F('High', 'Submitted sitemap has errors', 'Google could not process part of the sitemap, so some pages are not being discovered through it.', 'Open Search Console → Sitemaps → ' + s.path + ', fix the listed errors, resubmit.', s.errors + ' error(s), ' + s.warnings + ' warning(s) on ' + s.path, [s.path], null, 100);
    else if (s.warnings) F('Medium', 'Submitted sitemap has warnings', 'Warnings usually mean URLs with redirects, noindex or other inconsistencies.', 'Open Search Console → Sitemaps → ' + s.path + ' and clean the listed URLs.', s.warnings + ' warning(s) on ' + s.path, [s.path], null, 100);
    const dl = s.downloaded ? (Date.now() - new Date(s.downloaded).getTime()) / 864e5 : null;
    if (dl != null && dl > 30) F('Medium', 'Google has not read the sitemap for over a month', 'A sitemap Google stops reading usually failed or moved; updates to your pages reach Google late.', 'Resubmit the sitemap in Search Console and check it still returns 200 with valid XML.', s.path + ' last downloaded ' + s.downloaded.slice(0, 10), [s.path], null, 100);
    if (s.pending) F('Low', 'Sitemap submission still pending in Search Console', 'Google has not processed the sitemap yet.', 'Check again in a few days; if it stays pending, resubmit.', s.path, [s.path], null, 100);
  }
  if (sitemaps.length && !sitemaps.some(s => s.errors)) works.push('Sitemap submitted to Search Console (' + sitemaps.reduce((n, s) => n + s.urls, 0) + ' URLs, last read ' + ((sitemaps.find(s => s.downloaded) || {}).downloaded || 'n/a').slice(0, 10) + ')');
  const byKind = {}; reqs.forEach((q, i) => { byKind[q.kind] = byKind[q.kind] || []; byKind[q.kind].push({ q, r: res[i] }); });
  const tot = rowsOf(((byKind.totals || [])[0] || {}).r)[0]; search_console.totals = tot ? { clicks: Number(tot.clicks) || 0, impressions: Number(tot.impressions) || 0, ctr: Number(tot.ctr) || 0, position: +(Number(tot.position) || 0).toFixed(1), period: plan.range } : null;
  const pagesRows = rowsOf(((byKind.pages || [])[0] || {}).r).map(x => ({ page: x.keys[0], clicks: Number(x.clicks) || 0, impressions: Number(x.impressions) || 0, ctr: Number(x.ctr) || 0, position: +(Number(x.position) || 0).toFixed(1) }));
  const queryRows = rowsOf(((byKind.queries || [])[0] || {}).r).map(x => ({ query: x.keys[0], clicks: Number(x.clicks) || 0, impressions: Number(x.impressions) || 0, ctr: Number(x.ctr) || 0, position: +(Number(x.position) || 0).toFixed(1) }));
  search_console.top_pages = pagesRows.slice(0, 10); search_console.top_queries = queryRows.slice(0, 10); search_console.pages_with_impressions = pagesRows.length; search_console.queries_with_impressions = queryRows.length;
  const errs = Object.values(byKind).flat().map(x => gErr(x.r)).filter(Boolean); if (errs.length) search_console.request_errors = [...new Set(errs)].slice(0, 3);
  if (search_console.totals) {
    const t = search_console.totals;
    works.push('Search Console (last 28 days): ' + t.clicks + ' clicks from ' + t.impressions + ' impressions, average position ' + t.position);
    if (t.impressions >= 500 && t.position <= 10 && t.ctr < 0.01) F('Medium', 'Very low click-through rate for a site ranking on page 1', 'Titles and descriptions are not winning the click even where you rank well.', 'Rewrite the titles and meta descriptions of the pages with the most impressions (lead with the outcome, add a number, match the query wording).', (t.ctr * 100).toFixed(2) + '% CTR at average position ' + t.position + ' over ' + t.impressions + ' impressions', [], null, 100);
    const noClick = pagesRows.filter(p => p.impressions >= 50 && p.clicks === 0);
    if (noClick.length) F('Low', 'Pages shown in Google but never clicked', 'These pages earn impressions without clicks: the snippet does not match what searchers want, or they rank too low to be seen.', 'Check each page\'s main query, rewrite its title and description, and strengthen the page for that query.', noClick.length + ' page(s) with 50+ impressions and 0 clicks in 28 days', noClick.map(p => p.page), noClick.length, pagesRows.length ? Math.round(noClick.length / pagesRows.length * 100) : 100);
    if (sitemapKnown) { const shownNotInSitemap = pagesRows.filter(p => !sitemapUrls.includes(key(p.page)) && p.impressions >= 20); search_console.not_in_sitemap_but_shown = shownNotInSitemap.map(p => p.page).slice(0, 10);
      if (shownNotInSitemap.length >= 3) F('Low', 'Pages Google shows in search are missing from the sitemap', 'Google found these pages on its own; listing them in the sitemap keeps their updates flowing and confirms they are meant to rank.', 'Add them to the sitemap (or set the right canonical / noindex if they should not rank).', shownNotInSitemap.length + ' page(s) with impressions are not in sitemap.xml', shownNotInSitemap.map(p => p.page), shownNotInSitemap.length, 100); }
  }
  const insp = (byKind.inspect || []).map(x => { const r = x.r || {}; const ir = (r.inspectionResult || {}).indexStatusResult || null; const rr = (r.inspectionResult || {}).richResultsResult || null;
    return { url: x.q.inspect_url, error: r.error ? gErr(r) : (ir ? null : 'no result'), verdict: ir ? ir.verdict || '' : '', coverage: ir ? ir.coverageState || '' : '', indexed: ir ? ir.verdict === 'PASS' : null, robots: ir ? ir.robotsTxtState || '' : '', last_crawl: ir ? ir.lastCrawlTime || '' : '', google_canonical: ir ? ir.googleCanonical || '' : '', user_canonical: ir ? ir.userCanonical || '' : '', rich: rr && rr.detectedItems ? rr.detectedItems.map(d => d.richResultType).filter(Boolean) : [] }; });
  search_console.inspections = insp;
  const ok = insp.filter(i => !i.error); const coverage = {}; for (const i of ok) coverage[i.coverage || i.verdict || 'unknown'] = (coverage[i.coverage || i.verdict || 'unknown'] || 0) + 1; search_console.coverage = coverage;
  const notIdx = ok.filter(i => i.indexed === false); search_console.not_indexed = notIdx.map(i => ({ url: i.url, reason: i.coverage }));
  if (ok.length) {
    const share = Math.round(notIdx.length / ok.length * 100);
    if (notIdx.length && share >= 20) F('High', 'A large share of important pages is not indexed by Google', 'Pages that Google has not indexed cannot rank at all, whatever their content.', 'Open each URL in Search Console\'s URL inspection, fix the stated reason (crawled but not indexed usually means thin or duplicate content; discovered but not indexed means too few internal links), then request indexing.', notIdx.length + ' of ' + ok.length + ' sampled pages: ' + Object.entries(coverage).filter(([k]) => !/indexed/i.test(k) || /not indexed/i.test(k)).map(([k, v]) => v + ' × ' + k).join(', '), notIdx.map(i => i.url), notIdx.length, share);
    else if (notIdx.length) F('Medium', 'Some sampled pages are not indexed by Google', 'These pages cannot rank until Google indexes them.', 'Check the reason in Search Console\'s URL inspection, strengthen internal links to them and request indexing.', notIdx.map(i => i.coverage).filter((v, k, a) => a.indexOf(v) === k).join('; '), notIdx.map(i => i.url), notIdx.length, share);
    else works.push('All ' + ok.length + ' sampled pages are indexed by Google');
    const robotsBlocked = ok.filter(i => /disallow|blocked/i.test(i.robots)); if (robotsBlocked.length) F('High', 'Important pages blocked by robots.txt', 'Google cannot crawl these pages, so it cannot rank them on their content.', 'Remove the Disallow rule that matches them in robots.txt.', robotsBlocked.map(i => i.robots).join(', '), robotsBlocked.map(i => i.url), robotsBlocked.length, Math.round(robotsBlocked.length / ok.length * 100));
    const canon = ok.filter(i => i.indexed && i.google_canonical && !same(i.google_canonical, i.url)); search_console.canonical_mismatch = canon.map(i => ({ url: i.url, google_canonical: i.google_canonical }));
    if (canon.length) F('Medium', 'Google chose a different canonical URL than the page itself', 'Google treats these pages as duplicates of another URL, so they do not rank on their own.', 'Make each page clearly distinct, set its canonical tag to itself, and link to that version consistently.', canon.map(i => path(i.url) + ' → ' + i.google_canonical).join('; ').slice(0, 300), canon.map(i => i.url), canon.length, Math.round(canon.length / ok.length * 100));
    const notSubmitted = ok.filter(i => /not submitted in sitemap/i.test(i.coverage)); if (notSubmitted.length >= 3) F('Low', 'Indexed pages that are not in the submitted sitemap', 'Google indexed them anyway, but the sitemap is incomplete.', 'Regenerate the sitemap to include every indexable page.', notSubmitted.length + ' sampled pages are "indexed, not submitted in sitemap"', notSubmitted.map(i => i.url), notSubmitted.length, Math.round(notSubmitted.length / ok.length * 100));
    const stale = ok.filter(i => i.indexed && i.last_crawl && (Date.now() - new Date(i.last_crawl).getTime()) / 864e5 > 60); if (stale.length && stale.length / ok.length >= 0.5) F('Low', 'Google crawls important pages rarely', 'Pages Google visits only every few months pick up changes late; it usually means few internal links and little fresh content.', 'Update and interlink key pages regularly; keep the sitemap lastmod dates honest.', stale.length + ' of ' + ok.length + ' sampled pages last crawled over 60 days ago', stale.map(i => i.url), stale.length, Math.round(stale.length / ok.length * 100));
    const rich = [...new Set(ok.flatMap(i => i.rich))]; search_console.rich_results = rich; if (rich.length) works.push('Google detects rich results on sampled pages: ' + rich.join(', '));
    const errCount = insp.length - ok.length; if (errCount) search_console.inspection_errors = errCount;
  }
}
const site_structure = { crawled_pages: pages.length, indexable_pages: indexablePages.length, depth_buckets: depthBuckets, within_3_clicks_pct: withDepth ? Math.round(within3 / withDepth * 100) : null, sections: topSections, sitemap: { url: plan.sitemap_url, status: smStatus, urls: sitemapUrls.length, is_index: isIndex, children: childCount }, indexable_not_in_sitemap: notInSitemap.length, sitemap_only: sitemapOnly.length, sitemap_broken: sitemapBroken.length, crawl_complete: crawlComplete };
return [{ json: { ...base, extra_findings: [...(base.extra_findings || []), ...findings], extra_works: [...(base.extra_works || []), ...works], search_console, site_structure } }];
