// Weekly performance report per site: e-mail HTML (KPI tiles, actions, tracked keywords, ladder pages, movers, opportunities, traffic, trends),
// the same document as a file for the PDF renderer, and the fields for the callback. Uses the AI brief when present, the facts otherwise.
const metrics = $('Site Metrics').all().map(i => i.json);
let briefs = []; try { briefs = $('Site Brief').all().map(i => (i.json && i.json.output && typeof i.json.output === 'object') ? i.json.output : null); } catch (e) { briefs = []; }
const esc = (s) => String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const n = (v) => (Number(v) || 0).toLocaleString('en-GB');
const r1 = (v) => Math.round((Number(v) || 0) * 10) / 10;
const pct = (cur, prev) => prev > 0 ? Math.round((cur - prev) / prev * 100) : (cur > 0 ? null : 0);
const pctS = (v) => v == null ? 'new' : (v > 0 ? '▲ ' : v < 0 ? '▼ ' : '') + Math.abs(v) + '%';
const posS = (v) => !v ? '—' : '#' + r1(v);
const dcol = (v, invert) => v == null ? '#475569' : ((invert ? -v : v) > 0 ? '#15803d' : (invert ? -v : v) < 0 ? '#b91c1c' : '#475569');
const td = 'style="padding:4px 8px;border:1px solid #cbd5e1;font-size:13px;vertical-align:top"', th = 'style="padding:4px 8px;border:1px solid #cbd5e1;background:#f1f5f9;text-align:left;font-size:12px"';
const table = (headers, rows, empty) => rows.length ? '<table style="border-collapse:collapse;margin:6px 0;max-width:100%">' + '<tr>' + headers.map(h => '<th ' + th + '>' + esc(h) + '</th>').join('') + '</tr>' + rows.map(r => '<tr>' + r.map(c => '<td ' + td + '>' + c + '</td>').join('') + '</tr>').join('') + '</table>' : '<p style="color:#64748b;font-size:13px">' + esc(empty || 'nothing to show') + '</p>';
const tile = (label, value, delta, color) => '<td style="padding:8px 12px;border:1px solid #e2e8f0;min-width:110px;vertical-align:top"><div style="font-size:11px;color:#64748b;text-transform:uppercase">' + esc(label) + '</div><div style="font-size:20px;font-weight:700">' + value + '</div><div style="font-size:12px;color:' + (color || '#475569') + '">' + delta + '</div></td>';
const h3 = (t) => '<h3 style="margin:18px 0 4px;font-size:15px;color:#0f172a">' + esc(t) + '</h3>';
const path = (u) => { const p = String(u || '').replace(/^https?:\/\/[^\/]+/i, ''); return p || '/'; };
const link = (u) => u ? '<a href="' + esc(u) + '" style="color:#1d4ed8">' + esc(path(u)) + '</a>' : '—';
const deltaS = (cur, prev) => { const d = cur - prev; return (d > 0 ? '<span style="color:#15803d">+' + n(d) + '</span>' : d < 0 ? '<span style="color:#b91c1c">' + n(d) + '</span>' : '0'); };
return metrics.map((m, i) => {
  const b = briefs[i] || null; const G = m.gsc, A = m.ga4;
  const period = m.period.current.start + ' to ' + m.period.current.end;
  const sa = m.service_account_email || '<i>(service-account e-mail: ask your administrator)</i>';
  let html = '<div style="font-family:Segoe UI,Helvetica,Arial,sans-serif;color:#0f172a;max-width:860px">';
  html += '<h2 style="margin:0 0 2px;font-size:20px">SEO performance: ' + esc(m.domain) + '</h2><p style="margin:0 0 10px;color:#64748b;font-size:13px">Last 28 days (' + esc(period) + ') vs the 28 days before · week ' + m.weeks_tracked + ' of tracking' + (m.on_demand ? ' · on-demand run' : '') + '</p>';
  if (b) { html += '<div style="background:#f8fafc;border-left:4px solid #1d4ed8;padding:10px 12px;margin:8px 0"><div style="font-weight:700;font-size:15px">' + esc(b.headline) + '</div><p style="margin:6px 0 0;font-size:14px">' + esc(b.summary) + '</p>' + ((b.highlights || []).length ? '<ul style="margin:6px 0 0;padding-left:18px;font-size:13px">' + b.highlights.map(x => '<li>' + esc(x) + '</li>').join('') + '</ul>' : '') + '</div>'; }
  const hard = m.alerts.filter(a => a.level === 'high' || a.level === 'medium');
  if (hard.length) html += '<div style="background:#fef2f2;border-left:4px solid #b91c1c;padding:8px 12px;margin:8px 0;font-size:13px"><b>Alerts</b><ul style="margin:4px 0 0;padding-left:18px">' + hard.map(a => '<li>' + esc(a.text) + '</li>').join('') + '</ul></div>';
  if (!G.connected || !A.connected) html += '<div style="background:#fffbeb;border-left:4px solid #d97706;padding:8px 12px;margin:8px 0;font-size:13px"><b>Connect Google to get real data</b><ol style="margin:4px 0 0;padding-left:18px">' +
    (!G.connected ? '<li><b>Search Console:</b> open <a href="https://search.google.com/search-console/users">Settings → Users and permissions</a> for ' + esc(m.domain) + ' and add <b>' + sa + '</b> with <i>Full</i> permission. ' + (G.error ? '<span style="color:#64748b">(' + esc(G.error) + ')</span>' : '') + '</li>' : '') +
    (!A.connected ? '<li><b>Google Analytics 4:</b> Admin → Property access management → add the same e-mail as <i>Viewer</i>. The property is detected automatically from its web stream URL; or register the site again with its GA4 property ID. ' + (A.error ? '<span style="color:#64748b">(' + esc(A.error) + ')</span>' : '') + '</li>' : '') +
    '</ol><p style="margin:4px 0 0">The next weekly report (or an on-demand run) picks the access up automatically.</p></div>';
  let tiles = '';
  if (G.connected) tiles += tile('Clicks', n(G.totals.cur.clicks), pctS(G.deltas.clicks_pct) + (G.deltas.yoy_clicks_pct != null ? ' · ' + pctS(G.deltas.yoy_clicks_pct) + ' YoY' : ''), dcol(G.deltas.clicks_pct)) + tile('Impressions', n(G.totals.cur.impressions), pctS(G.deltas.impressions_pct), dcol(G.deltas.impressions_pct)) + tile('CTR', (G.totals.cur.ctr * 100).toFixed(1) + '%', (G.deltas.ctr_pts > 0 ? '+' : '') + G.deltas.ctr_pts + ' pts', dcol(G.deltas.ctr_pts)) + tile('Avg position', posS(G.totals.cur.position), G.deltas.position == null ? '—' : (G.deltas.position > 0 ? '▲ ' : G.deltas.position < 0 ? '▼ ' : '') + Math.abs(G.deltas.position) + ' places', dcol(G.deltas.position));
  if (A.connected) { const ps = pct(A.organic.cur.sessions, A.organic.prev.sessions), pk = pct(A.organic.cur.key_events, A.organic.prev.key_events); tiles += tile('Organic sessions', n(A.organic.cur.sessions), pctS(ps) + ' · ' + A.organic_share + '% of all sessions', dcol(ps)) + tile('Key events (organic)', n(A.organic.cur.key_events), pctS(pk) + ' · ' + n(A.organic.cur.engaged) + ' engaged sessions', dcol(pk)); }
  if (tiles) html += '<table cellspacing="6" style="border-collapse:separate;margin:8px 0"><tr>' + tiles + '</tr></table>';
  const acts = (b && Array.isArray(b.actions) && b.actions.length) ? b.actions.slice(0, 6).map(a => ({ action: a.action, why: a.why, keyword: a.keyword, url: a.url })) : m.actions.slice(0, 6);
  const withBody = m.actions.filter(a => a.api_body);
  html += h3('Do this week') + (acts.length ? '<ol style="margin:4px 0;padding-left:20px;font-size:14px">' + acts.map(a => '<li style="margin:4px 0"><b>' + esc(a.action) + '</b>' + (a.why ? '<br><span style="color:#475569;font-size:13px">' + esc(a.why) + '</span>' : '') + '</li>').join('') + '</ol>' : '<p style="font-size:13px;color:#64748b">Nothing urgent this week.</p>');
  if (withBody.length) html += '<p style="font-size:13px">Start the work with one click: open the <a href="' + esc(m.form_url) + '">SEO Assistant form</a> ("I know my keyword") or send one of these to the API (' + esc(m.api_url) + '):</p>' + withBody.slice(0, 3).map(a => '<pre style="background:#f1f5f9;padding:8px;font-size:11px;white-space:pre-wrap">' + esc(JSON.stringify(a.api_body)) + '</pre>').join('');
  // v4.5: the growth monitors' latest results (AI Visibility Tracker Mon 07:00, Backlink Monitor Mon 07:30, Audit Scheduler monthly)
  const latest2 = (name) => { try { return $(name).all().map(x => x.json).filter(r => r && r.site_id === m.site_id && !r.error).sort((x, y) => String(y.checked_at || y.audited_at).localeCompare(String(x.checked_at || x.audited_at))).slice(0, 2); } catch (e) { return []; } };
  const [av, av0] = latest2('Load AI Visibility (Site)'), [bl, bl0] = latest2('Load Backlink Snapshots (Site)'), [au, au0] = latest2('Load Audits (Site)');
  if (av || bl || au) {
    const dp = (cur, prev) => prev == null ? '' : (cur - prev > 0 ? ' <span style="color:#15803d">▲' + r1(cur - prev) + '</span>' : cur - prev < 0 ? ' <span style="color:#b91c1c">▼' + r1(prev - cur) + '</span>' : '');
    const rows = [];
    if (av) { let comp = []; try { comp = JSON.parse(av.competitors_json || '[]'); } catch (e) {} rows.push(['<b>AI answers</b> (' + esc(String(av.checked_at).slice(0, 10)) + ')', 'named in ' + r1(av.mention_rate) + '%' + dp(Number(av.mention_rate), av0 ? Number(av0.mention_rate) : null) + ' · pages cited in ' + r1(av.citation_rate) + '% · share of voice ' + r1(av.share_of_voice) + '%' + (comp[0] ? ' (leader: ' + esc(comp[0].domain) + ' ' + comp[0].share + '%)' : '') + (av.alerts ? '<br><span style="color:#b91c1c">' + esc(av.alerts) + '</span>' : '')]); }
    if (bl) rows.push(['<b>Backlinks</b> (' + esc(String(bl.checked_at).slice(0, 10)) + ', ' + esc(bl.mode) + ')', n(bl.referring_domains) + ' referring domains' + dp(Number(bl.referring_domains), bl0 ? Number(bl0.referring_domains) : null) + ' · ' + n(bl.new_links) + ' new / ' + n(bl.lost_links) + ' lost' + (Number(bl.important_lost) ? ' · <b style="color:#b91c1c">' + bl.important_lost + ' important lost</b>' : '') + (Number(bl.spammy_new) ? ' · ' + bl.spammy_new + ' spammy' : '') + ' · spam score ' + n(bl.spam_score)]);
    if (au) rows.push(['<b>Technical audit</b> (' + esc(String(au.audited_at).slice(0, 10)) + ')', 'health ' + n(au.health_score) + '/100' + dp(Number(au.health_score), au0 ? Number(au0.health_score) : null) + ' (' + esc(au.grade) + ') · ' + n(au.critical) + ' critical, ' + n(au.high) + ' high, ' + n(au.medium) + ' medium · ' + n(au.pages_crawled) + ' pages crawled']);
    html += h3('AI search, backlinks and technical health') + table(['Monitor', 'Latest'], rows) + '<p style="font-size:12px;color:#64748b">Details in the AI-visibility, backlink and audit reports (separate e-mails).</p>';
  }
  if (m.tracked.length) html += h3('Tracked keywords') + table(['Keyword', 'Source', 'Search Console avg', 'Before', 'Live Google check', 'Clicks', 'Impr.', 'Ranking page'], m.tracked.map(t => [esc(t.keyword), esc(t.source === 'ladder' ? (t.rung === 4 ? 'ladder top' : 'ladder rung ' + t.rung) : t.source === 'blog' ? 'blog page' : 'your list'),
    G.connected ? posS(t.gsc_position) : '<span style="color:#94a3b8">connect GSC</span>', G.connected ? posS(t.gsc_prev_position) : '—', t.serp_position == null ? '—' : (t.serp_position > 0 ? '#' + t.serp_position : t.serp_position === 0 ? 'not in top 50' : 'check failed') + (t.serp_checked_at ? '<br><span style="color:#94a3b8;font-size:11px">' + esc(String(t.serp_checked_at).slice(0, 10)) + '</span>' : ''), n(t.clicks), n(t.impressions), link(t.page || t.serp_url)]));
  const C = m.console || { notices: [], last_checkin: null, checkin_due: false };
  if (C.notices.length || C.last_checkin || C.checkin_due) {
    html += h3('Search Console notices and monthly check-in');
    if (C.notices.length) html += table(['Received', 'Kind', 'Notice'], C.notices.slice(0, 8).map(n => [esc(String(n.received_at).slice(0, 10)), esc(n.kind.replace(/_/g, ' ')) + (n.severity === 'critical' ? ' <b style="color:#b91c1c">urgent</b>' : ''), esc(n.subject)]));
    else html += '<p style="font-size:13px;color:#64748b">No Search Console notification in the last 35 days' + (m.service_account_email ? '' : '') + '.</p>';
    if (C.last_checkin) { const ck = C.last_checkin; html += '<p style="font-size:13px"><b>Last check-in (' + esc(ck.month) + '):</b> manual action ' + (ck.manual_action ? '<b style="color:#b91c1c">yes</b>' : 'no') + ', security issue ' + (ck.security_issue ? '<b style="color:#b91c1c">yes</b>' : 'no') + (ck.csv_kind === 'reasons' ? '; Pages report: ' + n(ck.not_indexed_total) + ' pages not indexed' + ((ck.coverage.reasons || []).length ? ' (' + ck.coverage.reasons.slice(0, 3).map(r => esc(r.reason) + ' ' + n(r.pages)).join(', ') + ')' : '') : ck.csv_kind === 'chart' ? '; Pages chart: ' + n(ck.coverage.indexed_total) + ' indexed, ' + n(ck.not_indexed_total) + ' not indexed' : '') + (ck.notes ? '; notes: ' + esc(ck.notes.slice(0, 160)) : '') + '</p>'; }
    if (C.checkin_due) html += '<p style="font-size:13px;color:#b45309"><b>Monthly check-in due:</b> open the <a href="' + esc(m.form_url) + '">form</a> ("Search Console check-in"), answer two questions and upload the Pages report export (Search Console → Pages → Export). It covers what the API cannot see: manual actions, security issues and the site-wide index coverage.</p>';
  }
  if ((m.pending_publish || []).length) html += '<p style="font-size:13px;color:#b45309"><b>Written, waiting for your publish link:</b> ' + m.pending_publish.map(p => esc(p.keyword) + ' (' + p.days + ' days ago)').join(', ') + ' — report it through the <a href="' + esc(m.form_url) + '">form</a> ("I published a page") so indexing and positions are tracked.</p>';
  if (m.ladder_pages.length) html += h3('Your pages: index status') + table(['Page', 'Rung', 'Status', 'Indexed', 'Coverage', 'Last crawl'], m.ladder_pages.map(p => [link(p.url), p.rung === 4 ? 'top' : p.rung ? String(p.rung) : 'blog', esc(p.status), p.indexed == null ? '<span style="color:#94a3b8">' + esc(p.inspect_error || 'unknown') + '</span>' : (p.indexed ? '<span style="color:#15803d">yes</span>' : '<span style="color:#b91c1c">no</span>'), esc(p.coverage || '—'), esc(p.last_crawl ? String(p.last_crawl).slice(0, 10) : '—')]));
  if (G.connected) {
    html += h3('Quick wins: striking distance (positions 4-20)') + table(['Query', 'Position', 'Before', 'Impressions', 'Clicks', 'Page'], G.striking.slice(0, 10).map(q => [esc(q.query), posS(q.position), posS(q.prev_position), n(q.impressions), n(q.clicks), link(q.page)]), 'no query between positions 4 and 20 with enough impressions yet');
    if (G.ctr_gaps.length) html += h3('Low click-through for the position (rewrite titles)') + table(['Query', 'Position', 'Impressions', 'CTR', 'Expected', 'Page'], G.ctr_gaps.slice(0, 6).map(q => [esc(q.query), posS(q.position), n(q.impressions), (q.ctr * 100).toFixed(1) + '%', Math.round(q.expected_ctr * 100) + '%', link(q.page)]));
    html += h3('Query movers') + '<table style="border-collapse:collapse;width:100%"><tr><td style="vertical-align:top;padding-right:8px;width:50%"><b style="font-size:13px;color:#15803d">Winners</b>' + table(['Query', 'Clicks', 'Position'], G.winners.slice(0, 6).map(q => [esc(q.query), n(q.clicks) + ' (' + deltaS(q.clicks, q.prev_clicks) + ')', posS(q.position) + (q.prev_position ? ' <span style="color:#94a3b8">was ' + posS(q.prev_position) + '</span>' : '')]), 'no clear winners') + '</td><td style="vertical-align:top;width:50%"><b style="font-size:13px;color:#b91c1c">Losers</b>' + table(['Query', 'Clicks', 'Position'], G.losers.slice(0, 6).map(q => [esc(q.query), n(q.clicks) + ' (' + deltaS(q.clicks, q.prev_clicks) + ')', posS(q.position) + (q.prev_position ? ' <span style="color:#94a3b8">was ' + posS(q.prev_position) + '</span>' : '')]), 'no clear losers') + '</td></tr></table>';
    if (G.new_queries.length || G.lost_queries.length) html += '<p style="font-size:13px"><b>New queries:</b> ' + (G.new_queries.slice(0, 8).map(q => esc(q.query) + ' (' + n(q.impressions) + ' impr.)').join(', ') || 'none') + '<br><b>Lost queries:</b> ' + (G.lost_queries.slice(0, 8).map(q => esc(q.query) + ' (' + n(q.prev_clicks) + ' clicks before)').join(', ') || 'none') + '</p>';
    html += h3('Pages') + table(['Page', 'Clicks', 'Change', 'Impressions', 'Position'], G.top_pages.slice(0, 8).map(p => [link(p.page), n(p.clicks), deltaS(p.clicks, p.prev_clicks), n(p.impressions), posS(p.position)]));
    if (G.decaying_pages.length) html += '<p style="font-size:13px"><b style="color:#b91c1c">Decaying pages:</b> ' + G.decaying_pages.slice(0, 5).map(p => esc(path(p.page)) + ' (' + n(p.prev_clicks) + ' → ' + n(p.clicks) + ' clicks)').join('; ') + '</p>';
  }
  if (A.connected) html += h3('Traffic (GA4, organic search)') + '<p style="font-size:13px">Organic: <b>' + n(A.organic.cur.sessions) + '</b> sessions (' + pctS(pct(A.organic.cur.sessions, A.organic.prev.sessions)) + '), ' + n(A.organic.cur.engaged) + ' engaged, ' + n(A.organic.cur.key_events) + ' key events, ' + n(A.organic.cur.users) + ' users · all channels: ' + n(A.total.cur.sessions) + ' sessions' + (A.channels.length ? ' (' + A.channels.slice(0, 4).map(c => esc(c.channel) + ' ' + n(c.sessions)).join(', ') + ')' : '') + (A.detected ? ' · property ' + esc(A.property_id) + ' detected automatically' : '') + '</p>' + table(['Landing page', 'Organic sessions', 'Change', 'Engaged', 'Key events'], A.landing.slice(0, 8).map(l => [link(l.page), n(l.sessions), deltaS(l.sessions, l.prev_sessions), n(l.engaged), n(l.key_events)]));
  if (m.trends.length) html += h3('Search interest (Google Trends, 12 months)') + table(['Keyword', 'Direction', 'Last 4 weeks vs average', 'Peak', 'Rising related searches'], m.trends.map(t => [esc(t.keyword), t.error ? '<span style="color:#94a3b8">' + esc(t.error) + '</span>' : t.direction === 'sparse' ? '<span style="color:#94a3b8">too little search volume for a trend</span>' : esc(t.direction), (t.change_pct == null || t.direction === 'sparse') ? '—' : (t.change_pct > 0 ? '+' : '') + t.change_pct + '%', esc(t.peak_date ? String(t.peak_date).slice(0, 7) : '—'), esc((t.rising || []).slice(0, 4).map(r => r.query + ' (' + r.value + ')').join(', ') || '—')]));
  if (b && (b.watch || []).length) html += h3('Watch') + '<ul style="font-size:13px;margin:4px 0;padding-left:18px">' + b.watch.map(x => '<li>' + esc(x) + '</li>').join('') + '</ul>';
  html += '<p style="color:#64748b;font-size:12px;margin-top:16px">Search Console figures are final up to 3 days ago and are averages across devices and locations; the live Google check is one SERP sample from DataForSEO. Trends are a relative index (100 = peak of the year). Reports run every Monday' + (m.tracked.some(t => t.source === 'ladder') ? '; the keyword ladder gets its own progress e-mail' : '') + '. Reply to this e-mail to pause tracking.</p></div>';
  const hi = m.alerts.filter(a => a.level === 'high').length; const parts = [];
  if (G.connected) parts.push(n(G.totals.cur.clicks) + ' clicks ' + pctS(G.deltas.clicks_pct)); if (hi) parts.push(hi + ' alert' + (hi > 1 ? 's' : '')); if (G.connected && G.striking.length) parts.push(G.striking.length + ' quick win' + (G.striking.length > 1 ? 's' : ''));
  const subject = (G.connected ? '[SEO weekly] ' : '[SEO tracking] ') + m.domain + ' — ' + (parts.length ? parts.join(' · ') : 'connect Google Search Console to see real data');
  const file_name = 'seo-performance-' + m.domain.replace(/[^a-z0-9.]+/g, '-') + '-' + m.period.current.end + '.html';
  const doc = '<!DOCTYPE html><html><head><meta charset="utf-8"><title>' + esc(subject) + '</title></head><body style="margin:24px">' + html + '</body></html>';
  return { json: { ...m, brief: b, subject, html, file_name, status: 'progress', stage: 'site_tracker' }, binary: { data: { data: Buffer.from(doc, 'utf8').toString('base64'), mimeType: 'text/html', fileName: file_name, fileExtension: 'html' } } };
});
